import React, { createContext, useContext, useState, useEffect } from "react";

/* ─── Translation Dictionaries ──────────────────────────────────────────────── */
const TRANSLATIONS = {
  en: {
    // App Shell
    appName: "AgriBridge", beta: "Beta",
    farmer: "Farmer", consumer: "Consumer", deliveryAgent: "Delivery Agent",
    farmerPortal: "🌾 Farmer Portal", consumerPortal: "🛒 Consumer Portal", deliveryPortal: "🚚 Delivery Portal",
    logout: "Logout", darkMode: "Dark Mode", lightMode: "Light Mode",

    // Nav
    home: "Home", myProducts: "My Products", farmDashboard: "Farm Dashboard",
    aiHub: "AI Hub", mandiPrices: "Mandi Prices", farmSimulator: "Farm Simulator",
    farmingAcademy: "Farming Academy", messages: "Messages", govtSchemes: "Govt Schemes",
    weather: "Weather", browseMarket: "Browse Market", livePrices: "Live Prices",
    mapRoutes: "Map & Routes", myOrders: "My Orders", wishlist: "Wishlist",
    deliveryDashboard: "Delivery Dashboard",

    // Farmer Home
    goodMorning: "Good Morning", goodAfternoon: "Good Afternoon", goodEvening: "Good Evening",
    farmerGreeting: "🌾 Farmer Dashboard", readyToSell: "Ready to sell today?",
    totalRevenue: "Total Revenue", totalOrders: "Total Orders",
    pendingOrders: "Pending Orders", lowStockAlert: "Low Stock Alert",
    quickActions: "⚡ Quick Actions", todaysTip: "💡 Today's Farming Tip",
    recentOrders: "📦 Recent Orders Received",
    noOrdersYet: "No orders yet — list your products to start selling!",
    listProducts: "+ List Products",
    ordersCount: "Orders Placed", spentTotal: "Amount Spent", wishlistCount: "Wishlist Items",
    todaysDeals: "🔥 Today's Deals", latestOrders: "📋 Latest Orders",
    shopNow: "Shop Now", noOrders: "No orders placed yet.",
    farmingTip1: "Water your crops early morning to reduce evaporation by up to 30%.",
    farmingTip2: "Rotate crops each season to improve soil health and reduce pest pressure.",
    farmingTip3: "Test soil pH before applying fertilizers — ideal range is 6.0–7.0.",
    farmingTip4: "Use drip irrigation to save 40–60% water compared to flood irrigation.",
    farmingTip5: "Plant marigolds around your field — they naturally repel pests.",
    farmingTip6: "Keep a crop diary to track growth, inputs, and yields for better decisions.",
    cropCalendar: "📅 Crop Calendar",
    currentSeason: "Current Season",
    kharif: "Kharif (Jun–Oct)", rabi: "Rabi (Nov–Mar)", zaid: "Zaid (Mar–Jun)",
    suggestedCrops: "Suggested Crops",
    marketPulse: "📈 Market Pulse",

    // Consumer Home
    shopper: "Shopper",
    freshProduce: "Fresh produce direct from farmers",
    productsAvailable: "products available",
    browseMarketBtn: "🛒 Browse Fresh Market",
    liveRates: "📈 Live Prices",
    todaysDeals: "🔥 Today's Best Deals",
    topRated: "⭐ Top Rated",
    featuredFarmers: "👨‍🌾 Meet Your Farmers",
    trackOrder: "Track Your Order",
    continueShopping: "Continue Shopping",
    latestOrders: "📋 Recent Orders",
    dealBadge: "DEAL",
    verified: "✓ Verified",
    directFarmer: "🌾 Direct Farmer",
    addToCart: "Add to Cart",
    addedToCart: "Added!",
    inCart: "in cart",
    inStock: "In Stock", outOfStock: "Out of Stock",
    perKg: "/kg", perPiece: "/pc", perLitre: "/L",

    // Marketplace / Filters
    freshMarket: "🛒 Fresh Market",
    searchProducts: "Search products...",
    filters: "Filters",
    category: "Category", priceRange: "Price Range", minRating: "Min Rating",
    sortBy: "Sort By", inStockOnly: "In Stock Only",
    applyFilters: "Apply Filters", reset: "Reset",
    newestFirst: "Newest First", priceLowHigh: "Price: Low→High",
    priceHighLow: "Price: High→Low", topRatedSort: "Top Rated", inStockSort: "In Stock",
    noProductsFound: "No products match your filters",
    clearFilters: "Clear Filters",

    // Cart
    myCart: "My Cart", cartEmpty: "Your cart is empty",
    browseProducts: "Browse Products",
    subtotal: "Subtotal", gst: "GST (5%)", deliveryFree: "Delivery FREE",
    total: "Total", proceedCheckout: "Proceed to Checkout",
    couponCode: "Coupon Code", applyCoupon: "Apply",
    couponApplied: "✅ Coupon applied!", couponInvalid: "❌ Invalid coupon",
    discount: "Discount",
    estimatedDelivery: "Est. Delivery: 3-5 days",

    // Checkout
    checkout: "Checkout",
    step1: "Delivery Address", step2: "Payment", step3: "Confirm Order",
    fullName: "Full Name", phone: "Phone Number",
    houseFlat: "House / Flat / Building",
    areaStreet: "Area / Street / Locality",
    city: "City", pincode: "Pincode", state: "State",
    saveAddress: "Save this address",
    savedAddresses: "Saved Addresses", useThisAddress: "Use This",
    paymentMethod: "Payment Method",
    upi: "UPI", card: "Card", netBanking: "Net Banking",
    cod: "Cash on Delivery", wallet: "Wallet",
    upiId: "Enter UPI ID", scanQR: "Or scan QR code",
    cardNumber: "Card Number", expiryDate: "Expiry (MM/YY)", cvv: "CVV",
    selectBank: "Select Bank",
    walletBalance: "Wallet Balance",
    orderSummary: "Order Summary", deliveryTo: "Delivery To",
    payUsing: "Paying With",
    placeOrder: "Place Order",
    placingOrder: "Placing Order...",
    orderSuccess: "Order Placed Successfully! 🎉",
    orderId: "Order ID", expectedDelivery: "Expected Delivery",
    downloadInvoice: "Download Invoice",
    trackOrderBtn: "Track Order",
    continueShopping2: "Continue Shopping",

    // My Orders
    myOrdersTitle: "My Orders",
    noOrders: "No orders yet",
    orderDate: "Order Date", orderStatus: "Status", orderTotal: "Total",
    reorder: "Reorder",
    delivered: "Delivered", pending: "Pending", processing: "Processing",
    shipped: "Shipped", cancelled: "Cancelled",

    // Wishlist
    myWishlist: "My Wishlist",
    noWishlist: "Your wishlist is empty",
    removeFromWishlist: "Remove",
    addToCartFromWishlist: "Add to Cart",

    // FarmerMarket
    myProductsTitle: "🌾 My Product Listings",
    addProduct: "+ Add Product",
    searchListings: "Search listings...",
    editListing: "Edit Listing",
    addNewProduct: "Add New Product",
    productName: "Product Name *",
    categoryLabel: "Category *",
    unit: "Unit",
    retailPrice: "Retail Price (₹) *",
    bulkPrice: "Bulk Price (₹)",
    stockQty: "Stock Quantity",
    minBulkQty: "Min Bulk Qty",
    imageUrl: "Image URL",
    imagePreview: "Preview",
    saveListing: "Save Listing",
    saving: "Saving...",
    cancel: "Cancel",
    topSeller: "🏆 Top Seller", lowStock: "⚠️ Low Stock", newTag: "✨ New",
    noListings: "No listings yet — add your first product!",
    ordersReceived: "Orders Received",
    buyer: "Buyer", quantity: "Qty", unitPrice: "Unit Price",

    // Weather & Logistics
    weatherTitle: "🌦️ Weather & Logistics",
    weatherSubtitle: "Real-time weather alerts and transport cost calculator",
    liveWeather: "Live Weather",
    customCity: "Custom city...",
    search: "Search",
    fetchingWeather: "Fetching weather...",
    todaysFarmingAdvisory: "🌾 Today's Farming Advisory",
    feelsLike: "Feels",
    humidity: "Humidity", wind: "Wind", visibility: "Visibility",
    transportCalc: "Transport Cost Calculator",
    originLabel: "📍 Origin (Farm Location)",
    destinationLabel: "🎯 Destination (Market/Buyer)",
    vehicleType: "🚚 Vehicle Type",
    calcTransport: "📦 Calculate Transport Cost",
    calculating: "Calculating...",
    transportEstimate: "🧾 Transport Estimate",
    distance: "Distance", duration: "Duration", rate: "Rate", estCost: "Est. Cost",
    route: "Route",
    aboutCalc: "ℹ️ About This Calculator",
    aboutCalcDesc: "Uses Google Maps Distance Matrix API to calculate real road distances. Rates are estimated based on average market rates in India.",
    allMinistries: "All Ministries",

    // Govt Schemes
    schemesTitle: "Government Agricultural Schemes",
    schemesSubtitle: "Active schemes & subsidies for Indian farmers · Updated 2025",
    searchSchemes: "Search schemes by name or benefit...",
    activeSchemes: "Active Schemes",
    ministries: "Ministries",
    beneficiaries: "Beneficiaries",
    showing: "Showing",
    scheme: "scheme", schemes: "schemes",
    applyNow: "Apply",
    benefit: "Benefit", eligibility: "Eligibility", deadline: "Deadline",
    noSchemesFound: "No schemes found matching",

    // Chat
    chatTitle: "💬 Messages",
    chatSubtitle: "Connect directly with farmers and buyers",
    selectConversation: "Select a conversation to start chatting",
    typeMessage: "Type a message...",
    send: "Send",
    online: "Online", offline: "Offline",
    noMessages: "No messages yet. Say hello!",
    farmers: "Farmers", buyers: "Buyers", all: "All",

    // Map
    mapTitle: "🗺️ Farm & Market Map",
    mapSubtitle: "Locate nearby farmers, markets & your delivery route",
    mapLoading: "Loading map...",
    showFarmers: "Show Farmers",
    showMarkets: "Show Markets",
    showRoutes: "Show Routes",
    directions: "Directions",
    viewOnMap: "View on Map",

    // FarmSimulator
    simTitle: "🚜 Farm Simulator",
    simSubtitle: "Simulate your farm for the next season",
    cropType: "Crop Type",
    landSize: "Land Size (acres)",
    irrigationType: "Irrigation Type",
    soilType: "Soil Type",
    simulate: "Simulate",
    simulationResult: "Simulation Result",
    expectedYield: "Expected Yield",
    estimatedProfit: "Estimated Profit",
    waterRequirement: "Water Requirement",
    fertilizerCost: "Fertilizer Cost",
    laborCost: "Labor Cost",
    totalCost: "Total Cost",
    netProfit: "Net Profit",
    riskLevel: "Risk Level",
    recommendations: "Recommendations",

    // Farming Tutorials / Academy
    tutorialsTitle: "🎓 Farming Academy",
    tutorialsSubtitle: "Learn modern farming techniques",
    allCategories: "All",
    homeFarming: "Home Farming",
    microFarming: "Micro Farming",
    organic: "Organic",
    hydroponics: "Hydroponics",
    terrace: "Terrace",
    watchNow: "Watch Now",
    readMore: "Read More",
    duration: "Duration",
    difficulty: "Difficulty",
    beginner: "Beginner", intermediate: "Intermediate", advanced: "Advanced",
    noTutorials: "No tutorials found.",

    // AI Hub
    aiHubTitle: "🤖 AI Hub",
    aiHubSubtitle: "AI-powered tools for smart farming",
    fertilizerAdvisor: "Fertilizer Advisor",
    cropDiagnosis: "Crop Disease Diagnosis",
    yieldPredictor: "Yield Predictor",
    soilAnalysis: "Soil Analysis",
    farmingChatbot: "Farming Assistant",
    analyzeNow: "Analyze",
    analyzing: "Analyzing...",
    result: "Result",
    cropName: "Crop Name",
    soilTypeLabel: "Soil Type",
    symptomDesc: "Describe symptoms...",
    uploadPhoto: "Upload Photo",

    // Farmer Dashboard
    dashboardTitle: "📊 Farm Dashboard",
    salesOverview: "Sales Overview",
    inventoryStatus: "Inventory Status",
    revenueChart: "Revenue Chart",
    topProducts: "Top Products",
    stockLevel: "Stock Level",
    last7Days: "Last 7 Days",
    last30Days: "Last 30 Days",
    thisYear: "This Year",

    // Login
    welcomeTitle: "Welcome to AgriBridge",
    iAmA: "I am a...",
    farmerDesc: "Sell crops, manage farm, access AI tools & yield predictions",
    consumerDesc: "Buy fresh produce directly from farmers at best prices",
    deliveryDesc: "Pick up orders from farmers and deliver to consumers",
    continueAs: "Continue as",
    yourName: "Your Name (optional)",
    emailAddress: "Email Address *",
    sendOtp: "Send OTP →",
    checkInbox: "Check your inbox",
    sentCode: "We sent a 6-digit code to",
    devMode: "⚙️ Dev mode — OTP:",
    verifyLogin: "Verify & Login ✓",
    resendOtp: "Resend OTP",
    resendIn: "Resend OTP in",
    secureNote: "🔒 Secure · No password needed · OTP expires in 10 minutes",
    back: "← Back",

    // Delivery Dashboard
    deliveryAgentPortal: "Delivery Dashboard",
    availableOrders: "📦 Available",
    myDeliveries: "🚚 My Deliveries",
    earnings: "💰 Earnings",
    totalDeliveries: "Total Deliveries",
    completedDeliveries: "Completed",
    activeDeliveries: "Active Now",
    totalEarned: "Total Earned",
    acceptDelivery: "🚚 Accept Delivery",
    confirmPickup: "📦 Confirm Pickup",
    markInTransit: "🚚 Mark In Transit",
    markDelivered: "🎉 Mark Delivered",
    perDelivery: "per delivery",
    noAvailableOrders: "No orders available right now",
    noMyDeliveries: "No deliveries assigned yet",
    browseAvailable: "📦 Browse Available Orders",
    pickup: "Pickup", drop: "Drop",
    agentAssigned: "Agent Assigned",
    orderPickedUp: "Order Picked Up",
    outForDelivery: "Out for Delivery",
    refreshing: "Loading...", refresh: "⟳ Refresh",

    // Misc
    loading: "Loading...", error: "Error", retry: "Retry",
    viewAll: "View All", seeMore: "See More",
    copied: "Copied!", shareApp: "Share AgriBridge",
    poweredByAI: "Powered by AI",
    allRights: "AgriBridge — Empowering Indian Agriculture",

    // FarmerDashboard extra
    analyticsDashboard: "Analytics Dashboard",
    dashboardSubtitle: "Real-time insights · AI-powered price tracker · Farm intelligence",
    overview: "Overview", insights: "Insights",
    platformOverview: "Platform Overview",
    allTimeEarnings: "All time earnings",
    fulfilledOrders: "Fulfilled orders",
    avgRating: "Avg Rating",
    customerSatisfaction: "Customer satisfaction",
    activeProducts: "Active Products",
    listedOnMarket: "Listed on marketplace",
    thisWeeksRevenue: "This Week's Revenue",
    products: "Products", orders: "Orders", revenue: "Revenue", buyers: "Buyers",

    // FarmSimulator extra
    virtualFarmSim: "Virtual Farm Simulator",
    farmSimDesc: "Enter your farm details → AI simulates 5 best crop options",
    locationField: "🌍 Location (City, State)",
    landSizeField: "📐 Land Size (Acres)",
    budgetField: "💰 Budget (₹)",
    soilTypeField: "🏔️ Soil Type",
    seasonField: "🌦️ Season",
    simulating: "Simulating 5 Crops via Groq AI… (may take ~15s)",
    runSimulation: "🚜 Run Farm Simulation",
    aiRecommendedCrops: "5 AI-Recommended Crops (ranked by suitability)",

    // FarmingTutorials extra
    yourLevel: "🎯 Your Level",
    topicOptional: "Topic (optional)",
    generating: "Generating…",
    regenerate: "Regenerate",
    loadTutorials: "Load Tutorials",
    welcomeAcademy: "Welcome to the Farming Academy",
    academyDesc: "Get AI-powered tutorials for home farming, micro farming businesses, hydroponics, terrace gardens, and more — with YouTube video links and step-by-step guides.",
    loadAiTutorials: "🌱 Load AI Tutorials",

    // AIHub extra
    aiFarmIntelligence: "AI Farm Intelligence",
    aiSystemsOnline: "AI Systems Online",
    yieldPredictor: "📈 Yield Predictor",
    fertilizerAdvisor: "🌱 Fertilizer Advisor",
    soilHealth: "🔬 Soil Health",
    cropDoctor: "🩺 Crop Doctor",
    aiChatbot: "🤖 AI Chatbot",
    farmSimulator: "🚜 Farm Simulator",
    aiHubSubtitle: "6 specialized AI tools powered by frontier models",

    // MapView
    mapPageTitle: "🗺️ AgriBridge Map — Pune & Bibewadi",
    mapPageSubtitle: "Local farms, mandis, delivery partners & buyers in Bibewadi, Dhayari, Katraj & surrounding Pune areas",
    mapSearchPlaceholder: "🔍 Search name or city...",
    mapShow10km: "Show 10 km radius",
    mapLocations: "location", mapLocationsPlural: "locations",
    mapNoLocations: "No locations found.",
    mapLegend: "Legend",
    mapTypeFarm: "Farm", mapTypeStore: "Store / Mandi", mapTypeDelivery: "Delivery Partner", mapTypeBuyer: "Buyer",
    mapFilterAll: "All", mapFilterFarms: "Farms", mapFilterStores: "Stores", mapFilterDelivery: "Delivery", mapFilterBuyers: "Buyers",
    mapDetailDescription: "Description", mapDetailStock: "Stock", mapDetailTimings: "Timings",
    mapDetailFleet: "Fleet", mapDetailRate: "Rate", mapDetailContact: "Contact", mapDetailRating: "Rating",
    mapPoweredBy: "Map powered by Leaflet.js + OpenStreetMap — completely free, no API key required. Click any marker or sidebar card to see full details.",

    // FarmerDashboard hardcoded strings
    loadingDashboard: "Loading dashboard...",
    farmingTipLabel: "💡 Farming Tip of the Moment",
    monthlyRevenue: "Monthly Revenue (₹)",
    mostSoldCrops: "Most Sold Crops (qty in kg)",
    avgCustomerRating: "Avg Customer Rating by Product",
    cropSalesDistribution: "Crop Sales Distribution",
    revenueBreakdown: "💰 Revenue Breakdown",
    retailSales: "Retail Sales", bulkB2B: "Bulk/B2B", avgPerOrder: "Avg per Order",
    productHealth: "📦 Product Health",
    activeListings: "Active Listings", returnRate: "Return Rate",
    farmStatus: "🌾 Farm Status",
    currentSeasonLabel: "Current Season", nextHarvest: "Next Harvest", mspCoverage: "MSP Coverage",
    farmPerformanceScore: "Farm Performance Score",
    revenueGrowth: "Revenue Growth",
    productDiversity: "Product Diversity", marketReach: "Market Reach", onTimeDelivery: "On-Time Delivery",
    performanceRadar: "Performance Radar",
    aiGeneratedInsights: "🧠 AI-Generated Insights",
    noRevenueData: "No revenue data yet",
    noSalesData: "No sales data yet",
    noRatingData: "No rating data yet",
    noData: "No data",
    vsLastMonth: "% vs last month",
    marketAlert: "Market Alert: Rising Prices",
    marketAlertDesc: "Tomato & Onion prices up 15–20% this week due to reduced arrivals. Consider selling stored stock now. Check the Live Prices tab for real-time data.",
    customerSatisfaction: "Customer Satisfaction",
    products: "Products", orders: "Orders", revenue: "Revenue", rating: "Rating",

    // ── ConsumerMarket strings ──────────────────────────────────────────────
    freshMarket: "Fresh Market",
    farmFreshDirect: "Farm-fresh produce direct to you",
    searchPlaceholder: "Search vegetables, fruits, grains…",
    filters: "Filters",
    showingProducts: "Showing",
    productsLabel: "products",
    forSearch: "for",
    noProductsFound: "No products found",
    tryDifferentFilters: "Try different filters or search terms",
    clearFilters: "Clear Filters",
    addToCart: "Add to Cart",
    addedToCart: "Added to Cart!",
    myCart: "My Cart",
    cartEmpty: "Your cart is empty",
    addFreshProduce: "Add fresh produce to get started!",
    subtotal: "Subtotal",
    delivery: "Delivery",
    deliveryFree: "FREE",
    total: "Total",
    proceedToCheckout: "Proceed to Checkout",
    estDelivery: "Est. Delivery: 3-5 business days",
    couponPlaceholder: "Coupon code (e.g. FRESH10)",
    applyCoupon: "Apply",
    couponApplied: "Coupon applied!",
    couponInvalid: "Invalid coupon code.",
    inCart: "in cart",
    farmFreshBadge: "Farm-Fresh",
    retailLabel: "Retail",
    bulkLabel: "Bulk",
    perUnit: "per",
    minBulk: "min",
    hideReviews: "Hide Reviews",
    reviewsRate: "Reviews & Rate",
    yourReview: "Your Review",
    shareExperience: "Share your experience…",
    submitReview: "Submit Review",
    categoryLabel: "Category",
    priceRange: "Price Range",
    minimumRating: "Minimum Rating",
    sortBy: "Sort By",
    inStockOnly: "In Stock Only",
    resetBtn: "Reset",
    applyFilters: "Apply Filters",
    newestFirst: "Newest First",
    priceLowHigh: "Price: Low→High",
    priceHighLow: "Price: High→Low",
    topRated: "Top Rated",
    inStock: "In Stock",
    itemsInWishlist: "items in your Wishlist",
    itemInWishlist: "item in your Wishlist",
    allCategories: "All",
    gstLabel: "GST (5%)",

    // ── HomePage strings ────────────────────────────────────────────────────
    farmerHeroLine1: "GROW YOUR",
    farmerHeroLine2: "FARM INTO",
    farmerHeroLine3: "REVENUE.",
    consumerHeroLine1: "FRESH FARM",
    consumerHeroLine2: "PRODUCE,",
    consumerHeroLine3: "DIRECT.",
    farmerHeroDesc: "Stop juggling 12 different apps. AgriBridge brings your crops, marketplace, AI insights, and market data into one powerful platform.",
    farmerHeroAccent: "Join 2,400+ Indian farmers already earning more.",
    farmerCta1: "🌾 Explore Marketplace",
    farmerCta2: "▶ Try AI Tools",
    farmerFeature1: "✓ Free to join",
    farmerFeature2: "✓ No subscription",
    farmerFeature3: "✓ AI-powered insights",
    consumerHeroDesc: "Stop overpaying at supermarkets. AgriBridge connects you directly to verified Indian farmers — fresh produce, honest pricing, doorstep delivery.",
    consumerHeroAccent: "Save up to 40% vs retail — no middlemen, no markups.",
    consumerCta1: "🛒 Browse Fresh Produce",
    consumerCta2: "📦 My Orders",
    verifiedFarmers: "✓ Verified farmers only",
    freshGuaranteed: "✓ Fresh guaranteed",
    freeReturns: "✓ Free returns",
    livePricesBadge: "LIVE PRICES",
    platformFeaturesBadge: "PLATFORM FEATURES",
    everythingFarmerNeeds: "Everything a Farmer Needs",
    platformFeaturesDesc: "From AI-powered crop care to direct market access — one platform, infinite possibilities.",
    builtForEveryone: "BUILT FOR EVERYONE",
    whoUsesTitle: "Who Uses AgriBridge?",
    forFarmers: "For Farmers",
    forConsumers: "For Consumers",
    forBusinesses: "For Businesses",
    farmerTab1: "🌾 List your produce in minutes — reach thousands of buyers",
    farmerTab2: "🤖 AI-powered crop care: fertilizer schedules + disease diagnosis",
    farmerTab3: "💰 Get fair prices with transparent market data",
    farmerTab4: "🏛️ Discover every govt scheme you're eligible for",
    farmerTab5: "🌦️ Plan your harvest with precision weather forecasts",
    consumerTab1: "🛒 Buy fresh produce directly from verified Indian farmers",
    consumerTab2: "💵 Save up to 40% vs retail — no middlemen",
    consumerTab3: "🚚 Doorstep delivery in 3-5 business days",
    consumerTab4: "⭐ Ratings and reviews for every farmer",
    consumerTab5: "📦 Track your orders in real time",
    businessTab1: "🏭 Bulk procurement directly from farms",
    businessTab2: "📊 Real-time commodity price intelligence",
    businessTab3: "🤝 Verified farmer network across 34 states",
    businessTab4: "📜 Digital contracts and quality certificates",
    businessTab5: "🔁 Recurring order management dashboard",
    startAsFarmer: "Start as Farmer →",
    shopFreshProduce: "Shop Fresh Produce →",
    contactB2B: "Contact for B2B →",
    yourDashboard: "Your Dashboard",
    manageProducts: "Manage Products →",
    fullDashboard: "Full Dashboard →",
    recentOrdersLabel: "Recent Orders",
    thisSeasonLabel: "This season",
    allTimeLabel: "All time",
    needsActionLabel: "Needs action",
    itemsLt10: "Items < 10 qty",
    justJoined: "Just joined",
    classicView: "📋 Classic View",
    modernView: "🆕 Modern View",
    ourFarmers: "Our Farmers",
    viewAll: "View All",
    buyNow: "Buy Now →",
    shopNow: "Shop Now →",
    noOrdersYet: "No orders yet",
    messageBtn: "Message",
    verifiedBadge: "✓✓ Verified",
    ordersCount: "orders",
    featureMarketTitle: "Fresh Marketplace",
    featureMarketDesc: "Buy and sell fresh produce directly. Retail & bulk pricing with live inventory tracking.",
    featureAITitle: "AI Farm Intelligence",
    featureAIDesc: "Get fertilizer schedules, diagnose crop diseases, and chat with an AI agronomist 24/7.",
    featureWeatherTitle: "Weather & Forecasts",
    featureWeatherDesc: "Hyperlocal 7-day forecasts, soil temperature, and weather alerts for your farm.",
    featureMapTitle: "Farm Map & Routes",
    featureMapDesc: "Visualize your farm on an interactive map, track delivery routes, and find nearby mandis.",
    totalRevenueCard: "TOTAL REVENUE",
    activeFarmers: "Active Farmers",
    earningsView: "📊 Earnings View",
    totalSavings: "TOTAL SAVINGS",
    browseMarketCard: "Browse Market",
    justOrdered: "Just ordered",
    newBadge: "NEW:",
    newAICropDoctor: "NEW: AI Crop Doctor 2.0 — Live Now",
    newFarmToDoor: "NEW: Farm-to-Door Delivery — Now Available",
    searchByVoice: "Search by voice",
    byFarmer: "by",

    // ── FarmerMarket strings ────────────────────────────────────────────────
    myListings: "My Listings",
    addProduct: "Add Product",
    editProduct: "Edit Product",
    deleteProduct: "Delete Product",
    productName: "Product Name",
    description: "Description",
    category: "Category",
    retailPrice: "Retail Price (₹/unit)",
    bulkPrice: "Bulk Price (₹/unit)",
    minBulkQty: "Min Bulk Qty",
    stockQty: "Stock (kg)",
    unit: "Unit",
    imageUrl: "Image URL",
    saveProduct: "Save Product",
    cancelBtn: "Cancel",
    deleteConfirm: "Delete this product?",
    noListings: "No listings yet. Add your first product!",
    addFirstProduct: "Add First Product",
    perKg: "/kg",
    kgStock: "kg stock",
    reviewCount: "reviews",
    loadingProducts: "Loading your products...",
    productAdded: "Product added!",
    productUpdated: "Product updated!",
    productDeleted: "Product deleted.",
    saveChanges: "Save Changes",
    fromOrders: "From all orders",
    productsLabel: "products",
    noProductsFoundFm: "No matching products",
    tryDifferentFilters: "Try a different search or filter",
    noOrdersYet: "No orders yet",

    // ── Checkout / Orders / Wishlist strings ────────────────────────────────
    checkoutTitle: "Checkout",
    orderSummary: "Order Summary",
    shippingAddress: "Shipping Address",
    fullName: "Full Name",
    phone: "Phone",
    addressLine: "Address",
    city: "City",
    pincode: "Pincode",
    placeOrder: "Place Order",
    orderPlaced: "Order Placed!",
    orderPlacedDesc: "Your order has been placed successfully. You'll receive a confirmation shortly.",
    continueShopping: "Continue Shopping",
    myOrdersTitle: "My Orders",
    noOrdersDesc: "You haven't placed any orders yet.",
    startShopping: "Start Shopping",
    orderStatus: "Status",
    orderDate: "Date",
    wishlistTitle: "My Wishlist",
    wishlistEmpty: "Your wishlist is empty.",
    browseProducts: "Browse Products",
    removeFromWishlist: "Remove",

    // ── Delivery Dashboard ──────────────────────────────────────────────────
    availableOrders: "Available Orders",
    myDeliveries: "My Deliveries",
    acceptOrder: "Accept",
    markDelivered: "Mark Delivered",
    earningsToday: "Today's Earnings",
    totalDeliveries: "Total Deliveries",
    pendingPickup: "Pending Pickup",
    deliveryMap: "Delivery Map",
    noAvailableOrders: "No available orders right now.",
    noActiveDeliveries: "No active deliveries.",
    pickupFrom: "Pickup from",
    deliverTo: "Deliver to",
  },

  hi: {
    // App Shell
    appName: "एग्रीब्रिज", beta: "बीटा",
    farmer: "किसान", consumer: "उपभोक्ता", deliveryAgent: "डिलीवरी एजेंट",
    farmerPortal: "🌾 किसान पोर्टल", consumerPortal: "🛒 उपभोक्ता पोर्टल", deliveryPortal: "🚚 डिलीवरी पोर्टल",
    logout: "लॉग आउट", darkMode: "डार्क मोड", lightMode: "लाइट मोड",

    // Nav
    home: "होम", myProducts: "मेरे उत्पाद", farmDashboard: "फार्म डैशबोर्ड",
    aiHub: "AI हब", mandiPrices: "मंडी भाव", farmSimulator: "फार्म सिम्युलेटर",
    farmingAcademy: "कृषि अकादमी", messages: "संदेश", govtSchemes: "सरकारी योजनाएं",
    weather: "मौसम", browseMarket: "बाज़ार देखें", livePrices: "लाइव भाव",
    mapRoutes: "मैप और रास्ते", myOrders: "मेरे आर्डर", wishlist: "विशलिस्ट",
    deliveryDashboard: "डिलीवरी डैशबोर्ड",

    // Farmer Home
    goodMorning: "सुप्रभात", goodAfternoon: "शुभ दोपहर", goodEvening: "शुभ संध्या",
    farmerGreeting: "🌾 किसान डैशबोर्ड", readyToSell: "आज बेचने के लिए तैयार?",
    totalRevenue: "कुल आय", totalOrders: "कुल आर्डर",
    pendingOrders: "लंबित आर्डर", lowStockAlert: "कम स्टॉक चेतावनी",
    quickActions: "⚡ त्वरित कार्य", todaysTip: "💡 आज की कृषि टिप",
    recentOrders: "📦 हाल के प्राप्त आर्डर",
    noOrdersYet: "अभी तक कोई आर्डर नहीं — अपने उत्पाद सूचीबद्ध करें!",
    listProducts: "+ उत्पाद जोड़ें",
    ordersCount: "दिए गए आर्डर", spentTotal: "खर्च राशि", wishlistCount: "विशलिस्ट आइटम",
    todaysDeals: "🔥 आज के सौदे", latestOrders: "📋 ताज़े आर्डर",
    shopNow: "अभी खरीदें", noOrders: "अभी तक कोई आर्डर नहीं।",
    farmingTip1: "फसलों को सुबह जल्दी पानी दें — इससे 30% तक वाष्पीकरण कम होता है।",
    farmingTip2: "हर मौसम में फसल बदलें — इससे मिट्टी की सेहत और कीट नियंत्रण बेहतर होता है।",
    farmingTip3: "खाद डालने से पहले मिट्टी का pH जाँचें — आदर्श सीमा 6.0–7.0 है।",
    farmingTip4: "ड्रिप सिंचाई से बाढ़ सिंचाई की तुलना में 40–60% पानी बचता है।",
    farmingTip5: "खेत के चारों ओर गेंदे के फूल लगाएं — ये प्राकृतिक रूप से कीटों को दूर रखते हैं।",
    farmingTip6: "फसल डायरी रखें — इससे बेहतर निर्णय लेने में मदद मिलती है।",
    cropCalendar: "📅 फसल कैलेंडर",
    currentSeason: "वर्तमान मौसम",
    kharif: "खरीफ (जून–अक्टूबर)", rabi: "रबी (नवंबर–मार्च)", zaid: "जायद (मार्च–जून)",
    suggestedCrops: "सुझावित फसलें",
    marketPulse: "📈 बाज़ार स्पंदन",

    // Consumer Home
    shopper: "खरीदार",
    freshProduce: "किसानों से सीधे ताज़ी उपज",
    productsAvailable: "उत्पाद उपलब्ध",
    browseMarketBtn: "🛒 ताज़ा बाज़ार देखें",
    liveRates: "📈 लाइव भाव",
    ordersCount: "आर्डर", spentTotal: "खर्च", wishlistCount: "विशलिस्ट",
    todaysDeals: "🔥 आज के बेस्ट डील",
    topRated: "⭐ सर्वोत्तम रेटेड",
    featuredFarmers: "👨‍🌾 हमारे किसान",
    trackOrder: "आर्डर ट्रैक करें",
    continueShopping: "खरीदारी जारी रखें",
    latestOrders: "📋 हाल के आर्डर",
    dealBadge: "डील",
    verified: "✓ सत्यापित",
    directFarmer: "🌾 सीधे किसान से",
    addToCart: "कार्ट में डालें",
    addedToCart: "जोड़ा!",
    inCart: "कार्ट में",
    inStock: "उपलब्ध", outOfStock: "अनुपलब्ध",
    perKg: "/किलो", perPiece: "/नग", perLitre: "/लीटर",

    // Marketplace / Filters
    freshMarket: "🛒 ताज़ा बाज़ार",
    searchProducts: "उत्पाद खोजें...",
    filters: "फ़िल्टर",
    category: "श्रेणी", priceRange: "मूल्य सीमा", minRating: "न्यूनतम रेटिंग",
    sortBy: "क्रमबद्ध करें", inStockOnly: "केवल उपलब्ध",
    applyFilters: "फ़िल्टर लगाएं", reset: "रीसेट",
    newestFirst: "नवीनतम पहले", priceLowHigh: "मूल्य: कम→अधिक",
    priceHighLow: "मूल्य: अधिक→कम", topRatedSort: "सर्वोत्तम रेटेड", inStockSort: "उपलब्ध",
    noProductsFound: "कोई उत्पाद नहीं मिला",
    clearFilters: "फ़िल्टर हटाएं",

    // Cart
    myCart: "मेरी कार्ट", cartEmpty: "आपकी कार्ट खाली है",
    browseProducts: "उत्पाद देखें",
    subtotal: "उप-कुल", gst: "GST (5%)", deliveryFree: "डिलीवरी निःशुल्क",
    total: "कुल", proceedCheckout: "चेकआउट करें",
    couponCode: "कूपन कोड", applyCoupon: "लगाएं",
    couponApplied: "✅ कूपन लागू!", couponInvalid: "❌ अमान्य कूपन",
    discount: "छूट",
    estimatedDelivery: "अनुमानित डिलीवरी: 3-5 दिन",

    // Checkout
    checkout: "चेकआउट",
    step1: "डिलीवरी पता", step2: "भुगतान", step3: "आर्डर पुष्टि",
    fullName: "पूरा नाम", phone: "फोन नंबर",
    houseFlat: "मकान / फ्लैट / बिल्डिंग",
    areaStreet: "क्षेत्र / सड़क / मोहल्ला",
    city: "शहर", pincode: "पिनकोड", state: "राज्य",
    saveAddress: "यह पता सहेजें",
    savedAddresses: "सहेजे गए पते", useThisAddress: "यह उपयोग करें",
    paymentMethod: "भुगतान विधि",
    upi: "UPI", card: "कार्ड", netBanking: "नेट बैंकिंग",
    cod: "कैश ऑन डिलीवरी", wallet: "वॉलेट",
    upiId: "UPI ID दर्ज करें", scanQR: "या QR कोड स्कैन करें",
    cardNumber: "कार्ड नंबर", expiryDate: "समाप्ति (MM/YY)", cvv: "CVV",
    selectBank: "बैंक चुनें",
    walletBalance: "वॉलेट बैलेंस",
    orderSummary: "आर्डर सारांश", deliveryTo: "डिलीवरी पता",
    payUsing: "भुगतान विधि",
    placeOrder: "आर्डर दें",
    placingOrder: "आर्डर हो रहा है...",
    orderSuccess: "आर्डर सफलतापूर्वक दिया गया! 🎉",
    orderId: "आर्डर ID", expectedDelivery: "अनुमानित डिलीवरी",
    downloadInvoice: "चालान डाउनलोड करें",
    trackOrderBtn: "आर्डर ट्रैक करें",
    continueShopping2: "खरीदारी जारी रखें",

    // My Orders
    myOrdersTitle: "मेरे आर्डर",
    noOrders: "अभी कोई आर्डर नहीं",
    shopNow: "अभी खरीदें",
    orderDate: "आर्डर तिथि", orderStatus: "स्थिति", orderTotal: "कुल",
    reorder: "पुनः आर्डर",
    delivered: "डिलीवर हुआ", pending: "लंबित", processing: "प्रक्रिया में",
    shipped: "भेजा गया", cancelled: "रद्द",

    // Wishlist
    myWishlist: "मेरी विशलिस्ट",
    noWishlist: "विशलिस्ट खाली है",
    removeFromWishlist: "हटाएं",
    addToCartFromWishlist: "कार्ट में डालें",

    // FarmerMarket
    myProductsTitle: "🌾 मेरे उत्पाद",
    addProduct: "+ उत्पाद जोड़ें",
    searchListings: "सूची खोजें...",
    editListing: "सूची संपादित करें",
    addNewProduct: "नया उत्पाद जोड़ें",
    productName: "उत्पाद का नाम *",
    categoryLabel: "श्रेणी *",
    unit: "इकाई",
    retailPrice: "खुदरा मूल्य (₹) *",
    bulkPrice: "थोक मूल्य (₹)",
    stockQty: "स्टॉक मात्रा",
    minBulkQty: "न्यूनतम थोक मात्रा",
    imageUrl: "छवि URL",
    imagePreview: "पूर्वावलोकन",
    saveListing: "सहेजें",
    saving: "सहेजा जा रहा है...",
    cancel: "रद्द करें",
    topSeller: "🏆 टॉप सेलर", lowStock: "⚠️ कम स्टॉक", newTag: "✨ नया",
    noListings: "अभी कोई सूची नहीं — पहला उत्पाद जोड़ें!",
    ordersReceived: "प्राप्त आर्डर",
    buyer: "खरीदार", quantity: "मात्रा", unitPrice: "इकाई मूल्य",

    // Misc
    loading: "लोड हो रहा है...", error: "त्रुटि", retry: "पुनः प्रयास",
    viewAll: "सभी देखें", seeMore: "और देखें",
    copied: "कॉपी हो गया!", shareApp: "एग्रीब्रिज साझा करें",
    poweredByAI: "AI द्वारा संचालित",
    allRights: "एग्रीब्रिज — भारतीय कृषि को सशक्त बनाना",

    // Weather & Logistics
    weatherTitle: "🌦️ मौसम और लॉजिस्टिक्स",
    weatherSubtitle: "रियल-टाइम मौसम अलर्ट और परिवहन लागत कैलकुलेटर",
    liveWeather: "लाइव मौसम",
    customCity: "कस्टम शहर...",
    search: "खोजें",
    fetchingWeather: "मौसम लोड हो रहा है...",
    todaysFarmingAdvisory: "🌾 आज की कृषि सलाह",
    feelsLike: "महसूस",
    humidity: "आर्द्रता", wind: "पवन", visibility: "दृश्यता",
    transportCalc: "परिवहन लागत कैलकुलेटर",
    originLabel: "📍 मूल स्थान (खेत)",
    destinationLabel: "🎯 गंतव्य (मंडी/खरीदार)",
    vehicleType: "🚚 वाहन प्रकार",
    calcTransport: "📦 परिवहन लागत गणना करें",
    calculating: "गणना हो रही है...",
    transportEstimate: "🧾 परिवहन अनुमान",
    distance: "दूरी", duration: "समय", rate: "दर", estCost: "अनुमानित लागत",
    route: "मार्ग",
    aboutCalc: "ℹ️ इस कैलकुलेटर के बारे में",
    aboutCalcDesc: "वास्तविक सड़क दूरी कैलकुलेट करने के लिए Google Maps का उपयोग करता है। दर भारत की औसत दरों पर आधारित हैं।",
    allMinistries: "सभी मंत्रालय",

    // Govt Schemes
    schemesTitle: "सरकारी कृषि योजनाएं",
    schemesSubtitle: "किसानों के लिए सक्रिय योजनाएं और सब्सिडी",
    searchSchemes: "योजनाएं खोजें...",
    activeSchemes: "सक्रिय योजनाएं",
    ministries: "मंत्रालय",
    beneficiaries: "लाभार्थी",
    showing: "दिखा रहे हैं",
    scheme: "योजना", schemes: "योजनाएं",
    applyNow: "आवेदन करें",
    benefit: "लाभ", eligibility: "पात्रता", deadline: "अंतिम तिथि",
    noSchemesFound: "कोई योजना नहीं मिली",

    // Chat
    chatTitle: "💬 संदेश",
    chatSubtitle: "किसानों और खरीदारों से सीधे कनेक्ट करें",
    selectConversation: "चैट शुरू करने के लिए बातचीत चुनें",
    typeMessage: "संदेश लिखें...",
    send: "भेजें",
    online: "ऑनलाइन", offline: "ऑफलाइन",
    noMessages: "अभी कोई संदेश नहीं। नमस्ते कहें!",
    farmers: "किसान", buyers: "खरीदार", all: "सभी",

    // Map
    mapTitle: "🗺️ खेत और बाज़ार मैप",
    mapSubtitle: "नजदीकी किसानों, बाज़ारों और डिलीवरी रूट ढूंढें",
    mapLoading: "मैप लोड हो रहा है...",
    showFarmers: "किसान दिखाएं",
    showMarkets: "बाज़ार दिखाएं",
    showRoutes: "रास्ते दिखाएं",
    directions: "दिशा-निर्देश",
    viewOnMap: "मैप पर देखें",

    // FarmSimulator
    simTitle: "🚜 फार्म सिम्युलेटर",
    simSubtitle: "अगले मौसम के लिए अपने खेत का अनुकरण करें",
    cropType: "फसल प्रकार",
    landSize: "भूमि का आकार (एकड़)",
    irrigationType: "सिंचाई प्रकार",
    soilType: "मिट्टी का प्रकार",
    simulate: "अनुकरण करें",
    simulationResult: "अनुकरण परिणाम",
    expectedYield: "अनुमानित उपज",
    estimatedProfit: "अनुमानित लाभ",
    waterRequirement: "पानी आवश्यकता",
    fertilizerCost: "खाद लागत",
    laborCost: "श्रम लागत",
    totalCost: "कुल लागत",
    netProfit: "शुद्ध लाभ",
    riskLevel: "जोखिम स्तर",
    recommendations: "सुझाव",

    // Farming Tutorials
    tutorialsTitle: "🎓 कृषि अकादमी",
    tutorialsSubtitle: "आधुनिक कृषि तकनीकें सीखें",
    allCategories: "सभी",
    homeFarming: "घर की खेती",
    microFarming: "सूक्ष्म खेती",
    organic: "जैविक",
    hydroponics: "हाइड्रोपोनिक्स",
    terrace: "छति खेती",
    watchNow: "अभी देखें",
    readMore: "और पढ़ें",
    duration: "अवधि",
    difficulty: "कठिनाई",
    beginner: "शुरुआती", intermediate: "मध्यम", advanced: "उन्नत",
    noTutorials: "कोई ट्यूटोरियल नहीं मिला।",

    // AI Hub
    aiHubTitle: "🤖 AI हब",
    aiHubSubtitle: "स्मार्ट खेती के लिए AI उपकरण",
    fertilizerAdvisor: "खाद सलाहकार",
    cropDiagnosis: "फसल रोग निदान",
    yieldPredictor: "उपज भविष्यवक्ता",
    soilAnalysis: "मिट्टी विश्लेषण",
    farmingChatbot: "कृषि सहायक",
    analyzeNow: "विश्लेषण करें",
    analyzing: "विश्लेषण हो रहा है...",
    result: "परिणाम",
    cropName: "फसल का नाम",
    soilTypeLabel: "मिट्टी का प्रकार",
    symptomDesc: "लक्षण विवरित करें...",
    uploadPhoto: "फोटो अपलोड करें",

    // Farmer Dashboard
    dashboardTitle: "📊 फार्म डैशबोर्ड",
    salesOverview: "बिक्री अवलोकन",
    inventoryStatus: "स्टॉक स्थिति",
    revenueChart: "आय चार्ट",
    topProducts: "शीर्ष उत्पाद",
    stockLevel: "स्टॉक स्तर",
    last7Days: "पिछले 7 दिन",
    last30Days: "पिछले 30 दिन",
    thisYear: "इस वर्ष",

    // Login
    welcomeTitle: "AgriBridge में आपका स्वागत है",
    iAmA: "मैं हूँ...",
    farmerDesc: "फसल बेचें, खेत प्रबंधित करें, AI टूल उपयोग करें",
    consumerDesc: "किसानों से सीधे ताजा उत्पाद खरीदें",
    deliveryDesc: "किसानों से आर्डर उठाएं और ग्राहकों तक पहुंचाएं",
    continueAs: "जारी रखें बतौर",
    yourName: "आपका नाम (वैकल्पिक)",
    emailAddress: "ईमेल पता *",
    sendOtp: "OTP भेजें →",
    checkInbox: "इनबॉक्स जांचें",
    sentCode: "आपको 6-अंकों का कोड भेजा गया",
    devMode: "⚙️ डेव मोड — OTP:",
    verifyLogin: "सत्यापित करें और लॉगिन करें ✓",
    resendOtp: "OTP पुनः भेजें",
    resendIn: "OTP पुनः भेजें",
    secureNote: "🔒 सुरक्षित · कोई पासवर्ड नहीं · OTP 10 मिनट में एक्सपायर",
    back: "← वापस",

    // Delivery Dashboard
    deliveryAgentPortal: "डिलीवरी डैशबोर्ड",
    availableOrders: "📦 उपलब्ध",
    myDeliveries: "🚚 मेरी डिलीवरी",
    earnings: "💰 कमाई",
    totalDeliveries: "कुल डिलीवरी",
    completedDeliveries: "पूर्ण",
    activeDeliveries: "सक्रिय",
    totalEarned: "कुल कमाई",
    acceptDelivery: "🚚 डिलीवरी स्वीकार करें",
    confirmPickup: "📦 पिकअप कनफर्म करें",
    markInTransit: "🚚 ऐन रूट मार्क करें",
    markDelivered: "🎉 डिलीवरड मार्क करें",
    perDelivery: "प्रति डिलीवरी",
    noAvailableOrders: "अभी कोई आर्डर उपलब्ध नहीं",
    noMyDeliveries: "अभी कोई डिलीवरी निर्धारित नहीं",
    browseAvailable: "📦 उपलब्ध आर्डर देखें",
    pickup: "पिकअप", drop: "ड्रॉप",
    agentAssigned: "एजेंट नियुक्त",
    orderPickedUp: "आर्डर उठाया",
    outForDelivery: "डिलीवरी के लिए निकला",
    refreshing: "लोड हो रहा है...", refresh: "↳ रिफ्रेश",

    // FarmerDashboard extra
    analyticsDashboard: "विश्लेषण डैशबोर्ड",
    dashboardSubtitle: "रियल-टाइम इनसाइट्स · AI प्राइस ट्रैकर · फार्म इंटेलिजेंस",
    overview: "अवलोकन", insights: "अंतर्दृष्टि",
    platformOverview: "प्लेटफॉर्म अवलोकन",
    allTimeEarnings: "सभी समय की कमाई",
    fulfilledOrders: "पूर्ण आर्डर",
    avgRating: "औसत रेटिंग",
    customerSatisfaction: "ग्राहक संतोष",
    activeProducts: "सक्रिय उत्पाद",
    listedOnMarket: "बाज़ार में सूचीबद्ध",
    thisWeeksRevenue: "इस सप्ताह की आय",
    products: "उत्पाद", orders: "आर्डर", revenue: "आय", buyers: "खरीदार",

    // FarmSimulator extra
    virtualFarmSim: "वर्चुअल फार्म सिम्युलेटर",
    farmSimDesc: "खेत का विवरण दर्ज करें → AI 5 सर्वोत्तम फसल विकल्प देता है",
    locationField: "🌍 स्थान (शहर, राज्य)",
    landSizeField: "📐 भूमि का आकार (एकड़)",
    budgetField: "💰 बजट (₹)",
    soilTypeField: "🏔️ मिट्टी का प्रकार",
    seasonField: "🌦️ मौसम",
    simulating: "Groq AI से 5 फसलों का अनुकरण हो रहा है...",
    runSimulation: "🚜 फार्म सिम्युलेशन चलाएं",
    aiRecommendedCrops: "5 AI-अनुशंसित फसलें (उपयुक्तता के अनुसार)",

    // FarmingTutorials extra
    yourLevel: "🎯 आपका स्तर",
    topicOptional: "विषय (वैकल्पिक)",
    generating: "बन रहा है…",
    regenerate: "पुनः बनाएं",
    loadTutorials: "ट्यूटोरियल लोड करें",
    welcomeAcademy: "कृषि अकादमी में आपका स्वागत है",
    academyDesc: "घर की खेती, सूक्ष्म खेती, हाइड्रोपोनिक्स, छत की बागवानी आदि के लिए AI ट्यूटोरियल पाएं।",
    loadAiTutorials: "🌱 AI ट्यूटोरियल लोड करें",

    // AIHub extra
    aiFarmIntelligence: "AI कृषि बुद्धिमत्ता",
    aiSystemsOnline: "AI सिस्टम ऑनलाइन",
    yieldPredictor: "📈 उपज भविष्यवक्ता",
    fertilizerAdvisor: "🌱 खाद सलाहकार",
    soilHealth: "🔬 मिट्टी स्वास्थ्य",
    cropDoctor: "🩺 फसल डॉक्टर",
    aiChatbot: "🤖 AI चैटबॉट",
    farmSimulator: "🚜 फार्म सिम्युलेटर",
    aiHubSubtitle: "अग्रणी मॉडल द्वारा संचालित 6 AI उपकरण",

    // MapView
    mapPageTitle: "🗺️ एग्रीब्रिज मैप — पुणे और बिबवेवाड़ी",
    mapPageSubtitle: "बिबवेवाड़ी, धायरी, कात्रज और आसपास के पुणे क्षेत्रों में स्थानीय खेत, मंडियां, डिलीवरी पार्टनर और खरीदार",
    mapSearchPlaceholder: "🔍 नाम या शहर खोजें...",
    mapShow10km: "10 किमी त्रिज्या दिखाएं",
    mapLocations: "स्थान", mapLocationsPlural: "स्थान",
    mapNoLocations: "कोई स्थान नहीं मिला।",
    mapLegend: "लेजेंड",
    mapTypeFarm: "खेत", mapTypeStore: "दुकान / मंडी", mapTypeDelivery: "डिलीवरी पार्टनर", mapTypeBuyer: "खरीदार",
    mapFilterAll: "सभी", mapFilterFarms: "खेत", mapFilterStores: "दुकानें", mapFilterDelivery: "डिलीवरी", mapFilterBuyers: "खरीदार",
    mapDetailDescription: "विवरण", mapDetailStock: "स्टॉक", mapDetailTimings: "समय",
    mapDetailFleet: "वाहन", mapDetailRate: "दर", mapDetailContact: "संपर्क", mapDetailRating: "रेटिंग",
    mapPoweredBy: "मैप Leaflet.js + OpenStreetMap द्वारा संचालित — बिल्कुल मुफ्त, कोई API की नहीं चाहिए। विवरण देखने के लिए किसी मार्कर या साइडबार कार्ड पर क्लिक करें।",

    // FarmerDashboard hardcoded strings
    loadingDashboard: "डैशबोर्ड लोड हो रहा है...",
    farmingTipLabel: "💡 खेती की टिप",
    monthlyRevenue: "मासिक आय (₹)",
    mostSoldCrops: "सबसे अधिक बिकी फसलें (मात्रा किलो में)",
    avgCustomerRating: "उत्पाद अनुसार औसत रेटिंग",
    cropSalesDistribution: "फसल बिक्री वितरण",
    revenueBreakdown: "💰 आय विवरण",
    retailSales: "खुदरा बिक्री", bulkB2B: "थोक/B2B", avgPerOrder: "प्रति आर्डर औसत",
    productHealth: "📦 उत्पाद स्वास्थ्य",
    activeListings: "सक्रिय सूचियां", returnRate: "वापसी दर",
    farmStatus: "🌾 खेत की स्थिति",
    currentSeasonLabel: "वर्तमान मौसम", nextHarvest: "अगली फसल", mspCoverage: "MSP कवरेज",
    farmPerformanceScore: "खेती प्रदर्शन स्कोर",
    revenueGrowth: "आय वृद्धि",
    productDiversity: "उत्पाद विविधता", marketReach: "बाज़ार पहुंच", onTimeDelivery: "समय पर डिलीवरी",
    performanceRadar: "प्रदर्शन राडार",
    aiGeneratedInsights: "🧠 AI-जनित अंतर्दृष्टि",
    noRevenueData: "अभी कोई आय डेटा नहीं",
    noSalesData: "अभी कोई बिक्री डेटा नहीं",
    noRatingData: "अभी कोई रेटिंग डेटा नहीं",
    noData: "कोई डेटा नहीं",
    vsLastMonth: "% पिछले माह की तुलना में",
    marketAlert: "बाज़ार अलर्ट: बढ़ते भाव",
    marketAlertDesc: "इस सप्ताह टमाटर और प्याज के दाम 15-20% बढ़े हैं। संग्रहित स्टॉक अभी बेचने पर विचार करें।",
    customerSatisfaction: "ग्राहक संतुष्टि",
    products: "उत्पाद", orders: "आर्डर", revenue: "आय", rating: "रेटिंग",

    // ── ConsumerMarket strings ──────────────────────────────────────────────
    freshMarket: "ताज़ा बाज़ार",
    farmFreshDirect: "खेत से सीधे ताज़ी उपज आप तक",
    searchPlaceholder: "सब्ज़ियाँ, फल, अनाज खोजें…",
    filters: "फ़िल्टर",
    showingProducts: "दिखाए जा रहे",
    productsLabel: "उत्पाद",
    forSearch: "के लिए",
    noProductsFound: "कोई उत्पाद नहीं मिला",
    tryDifferentFilters: "अलग फ़िल्टर या खोज शब्द आज़माएं",
    clearFilters: "फ़िल्टर साफ़ करें",
    addToCart: "कार्ट में जोड़ें",
    addedToCart: "कार्ट में जोड़ा!",
    myCart: "मेरी कार्ट",
    cartEmpty: "आपकी कार्ट खाली है",
    addFreshProduce: "शुरू करने के लिए ताज़ी उपज जोड़ें!",
    subtotal: "उप-योग",
    delivery: "डिलीवरी",
    deliveryFree: "मुफ़्त",
    total: "कुल",
    proceedToCheckout: "चेकआउट करें",
    estDelivery: "अनुमानित डिलीवरी: 3-5 कार्य दिवस",
    couponPlaceholder: "कूपन कोड (जैसे FRESH10)",
    applyCoupon: "लागू करें",
    couponApplied: "कूपन लागू हुआ!",
    couponInvalid: "अमान्य कूपन कोड।",
    inCart: "कार्ट में",
    farmFreshBadge: "खेत-ताज़ा",
    retailLabel: "खुदरा",
    bulkLabel: "थोक",
    perUnit: "प्रति",
    minBulk: "न्यूनतम",
    hideReviews: "समीक्षाएं छुपाएं",
    reviewsRate: "समीक्षाएं और रेटिंग",
    yourReview: "आपकी समीक्षा",
    shareExperience: "अपना अनुभव साझा करें…",
    submitReview: "समीक्षा सबमिट करें",
    categoryLabel: "श्रेणी",
    priceRange: "मूल्य सीमा",
    minimumRating: "न्यूनतम रेटिंग",
    sortBy: "क्रमबद्ध करें",
    inStockOnly: "केवल स्टॉक में",
    resetBtn: "रीसेट",
    applyFilters: "फ़िल्टर लागू करें",
    newestFirst: "नवीनतम पहले",
    priceLowHigh: "मूल्य: कम→अधिक",
    priceHighLow: "मूल्य: अधिक→कम",
    topRated: "सर्वश्रेष्ठ रेटिंग",
    inStock: "स्टॉक में",
    itemsInWishlist: "आइटम आपकी विशलिस्ट में",
    itemInWishlist: "आइटम आपकी विशलिस्ट में",
    allCategories: "सभी",
    gstLabel: "जीएसटी (5%)",

    // ── HomePage strings ────────────────────────────────────────────────────
    farmerHeroLine1: "अपनी",
    farmerHeroLine2: "खेती को",
    farmerHeroLine3: "आमदनी में बदलें।",
    consumerHeroLine1: "खेत से",
    consumerHeroLine2: "ताज़ी उपज,",
    consumerHeroLine3: "सीधे आपके लिए।",
    farmerHeroDesc: "12 अलग-अलग ऐप्स को छोड़ें। AgriBridge आपकी फसलें, बाज़ार, AI अंतर्दृष्टि और मंडी डेटा एक शक्तिशाली प्लेटफॉर्म पर लाता है।",
    farmerHeroAccent: "2,400+ भारतीय किसानों से जुड़ें जो पहले से अधिक कमा रहे हैं।",
    farmerCta1: "🌾 बाज़ार देखें",
    farmerCta2: "▶ AI टूल आज़माएं",
    farmerFeature1: "✓ जुड़ना मुफ़्त",
    farmerFeature2: "✓ कोई सदस्यता नहीं",
    farmerFeature3: "✓ AI-संचालित अंतर्दृष्टि",
    consumerHeroDesc: "सुपरमार्केट में अधिक भुगतान बंद करें। AgriBridge आपको सत्यापित भारतीय किसानों से सीधे जोड़ता है — ताज़ी उपज, उचित मूल्य, दरवाजे पर डिलीवरी।",
    consumerHeroAccent: "खुदरा की तुलना में 40% तक बचाएं — कोई बिचौलिया नहीं।",
    consumerCta1: "🛒 ताज़ी उपज ब्राउज़ करें",
    consumerCta2: "📦 मेरे आर्डर",
    verifiedFarmers: "✓ केवल सत्यापित किसान",
    freshGuaranteed: "✓ ताज़गी की गारंटी",
    freeReturns: "✓ मुफ़्त वापसी",
    livePricesBadge: "लाइव भाव",
    platformFeaturesBadge: "प्लेटफॉर्म विशेषताएं",
    everythingFarmerNeeds: "किसान की हर ज़रूरत",
    platformFeaturesDesc: "AI-संचालित फसल देखभाल से सीधे बाज़ार पहुंच तक — एक प्लेटफॉर्म, अनंत संभावनाएं।",
    builtForEveryone: "सबके लिए बना",
    whoUsesTitle: "AgriBridge कौन उपयोग करता है?",
    forFarmers: "किसानों के लिए",
    forConsumers: "उपभोक्ताओं के लिए",
    forBusinesses: "व्यापारियों के लिए",
    farmerTab1: "🌾 मिनटों में अपनी उपज सूचीबद्ध करें — हज़ारों खरीदारों तक पहुंचें",
    farmerTab2: "🤖 AI फसल देखभाल: खाद कार्यक्रम + रोग निदान",
    farmerTab3: "💰 पारदर्शी बाज़ार डेटा से उचित मूल्य पाएं",
    farmerTab4: "🏛️ अपनी पात्र सरकारी योजनाएं खोजें",
    farmerTab5: "🌦️ सटीक मौसम पूर्वानुमान से फसल की योजना बनाएं",
    consumerTab1: "🛒 सत्यापित भारतीय किसानों से सीधे ताज़ी उपज खरीदें",
    consumerTab2: "💵 खुदरा की तुलना में 40% तक बचाएं — कोई बिचौलिया नहीं",
    consumerTab3: "🚚 3-5 कार्य दिवसों में दरवाजे पर डिलीवरी",
    consumerTab4: "⭐ हर किसान की रेटिंग और समीक्षाएं",
    consumerTab5: "📦 वास्तविक समय में ऑर्डर ट्रैक करें",
    businessTab1: "🏭 खेतों से सीधे थोक खरीद",
    businessTab2: "📊 वास्तविक समय की कमोडिटी मूल्य जानकारी",
    businessTab3: "🤝 34 राज्यों में सत्यापित किसान नेटवर्क",
    businessTab4: "📜 डिजिटल अनुबंध और गुणवत्ता प्रमाण पत्र",
    businessTab5: "🔁 आवर्ती ऑर्डर प्रबंधन डैशबोर्ड",
    startAsFarmer: "किसान के रूप में शुरू करें →",
    shopFreshProduce: "ताज़ी उपज खरीदें →",
    contactB2B: "B2B के लिए संपर्क करें →",
    yourDashboard: "आपका डैशबोर्ड",
    manageProducts: "उत्पाद प्रबंधित करें →",
    fullDashboard: "पूरा डैशबोर्ड →",
    recentOrdersLabel: "हाल के आर्डर",
    thisSeasonLabel: "इस मौसम",
    allTimeLabel: "सभी समय",
    needsActionLabel: "कार्रवाई चाहिए",
    itemsLt10: "10 से कम सामान",
    justJoined: "अभी जुड़े",
    classicView: "📋 क्लासिक व्यू",
    modernView: "🆕 मॉडर्न व्यू",
    ourFarmers: "हमारे किसान",
    viewAll: "सभी देखें",
    buyNow: "अभी खरीदें →",
    shopNow: "अभी खरीदें →",
    noOrdersYet: "अभी कोई आर्डर नहीं",
    messageBtn: "संदेश",
    verifiedBadge: "✓✓ सत्यापित",
    ordersCount: "आर्डर",
    featureMarketTitle: "ताज़ा बाज़ार",
    featureMarketDesc: "सीधे ताज़ी उपज खरीदें और बेचें। लाइव इन्वेंट्री ट्रैकिंग के साथ खुदरा और थोक मूल्य।",
    featureAITitle: "AI खेत बुद्धिमत्ता",
    featureAIDesc: "खाद कार्यक्रम प्राप्त करें, फसल रोगों का निदान करें और 24/7 AI कृषि विशेषज्ञ से चैट करें।",
    featureWeatherTitle: "मौसम और पूर्वानुमान",
    featureWeatherDesc: "आपके खेत के लिए हाइपरलोकल 7-दिन पूर्वानुमान, मिट्टी तापमान और मौसम अलर्ट।",
    featureMapTitle: "खेत नक्शा और मार्ग",
    featureMapDesc: "इंटरैक्टिव मानचित्र पर अपना खेत देखें, डिलीवरी मार्ग ट्रैक करें और पास की मंडियाँ खोजें।",
    totalRevenueCard: "कुल आमदनी",
    activeFarmers: "सक्रिय किसान",
    earningsView: "📊 कमाई देखें",
    totalSavings: "कुल बचत",
    browseMarketCard: "बाज़ार देखें",
    justOrdered: "अभी ऑर्डर किया",
    newBadge: "नया:",
    newAICropDoctor: "नया: AI फसल डॉक्टर 2.0 — अभी उपलब्ध",
    newFarmToDoor: "नया: खेत-से-दरवाज़ा डिलीवरी — अब उपलब्ध",
    searchByVoice: "आवाज़ से खोजें",
    byFarmer: "द्वारा",

    // ── FarmerMarket strings ────────────────────────────────────────────────
    myListings: "मेरी सूचियाँ",
    addProduct: "उत्पाद जोड़ें",
    editProduct: "उत्पाद संपादित करें",
    deleteProduct: "उत्पाद हटाएं",
    productName: "उत्पाद का नाम",
    description: "विवरण",
    category: "श्रेणी",
    retailPrice: "खुदरा मूल्य (₹/इकाई)",
    bulkPrice: "थोक मूल्य (₹/इकाई)",
    minBulkQty: "न्यूनतम थोक मात्रा",
    stockQty: "स्टॉक (किलो)",
    unit: "इकाई",
    imageUrl: "चित्र URL",
    saveProduct: "उत्पाद सहेजें",
    cancelBtn: "रद्द करें",
    deleteConfirm: "यह उत्पाद हटाएं?",
    noListings: "अभी कोई सूची नहीं। अपना पहला उत्पाद जोड़ें!",
    addFirstProduct: "पहला उत्पाद जोड़ें",
    perKg: "/किलो",
    kgStock: "किलो स्टॉक",
    reviewCount: "समीक्षाएं",
    loadingProducts: "आपके उत्पाद लोड हो रहे हैं...",
    productAdded: "उत्पाद जोड़ा!",
    productUpdated: "उत्पाद अपडेट हुआ!",
    productDeleted: "उत्पाद हटाया।",
    saveChanges: "परिवर्तन सहेजें",
    fromOrders: "सभी ऑर्डर से",
    productsLabel: "उत्पाद",
    noProductsFoundFm: "कोई मेल खाता उत्पाद नहीं",
    tryDifferentFilters: "अलग खोज या फ़िल्टर आज़माएं",
    noOrdersYet: "अभी तक कोई आर्डर नहीं",

    // ── Checkout / Orders / Wishlist strings ────────────────────────────────
    checkoutTitle: "चेकआउट",
    orderSummary: "ऑर्डर सारांश",
    shippingAddress: "शिपिंग पता",
    fullName: "पूरा नाम",
    phone: "फ़ोन",
    addressLine: "पता",
    city: "शहर",
    pincode: "पिनकोड",
    placeOrder: "ऑर्डर करें",
    orderPlaced: "ऑर्डर दिया गया!",
    orderPlacedDesc: "आपका ऑर्डर सफलतापूर्वक दिया गया है। जल्द ही पुष्टि मिलेगी।",
    continueShopping: "खरीदारी जारी रखें",
    myOrdersTitle: "मेरे आर्डर",
    noOrdersDesc: "आपने अभी तक कोई ऑर्डर नहीं दिया है।",
    startShopping: "खरीदारी शुरू करें",
    orderStatus: "स्थिति",
    orderDate: "तारीख",
    wishlistTitle: "मेरी विशलिस्ट",
    wishlistEmpty: "आपकी विशलिस्ट खाली है।",
    browseProducts: "उत्पाद ब्राउज़ करें",
    removeFromWishlist: "हटाएं",

    // ── Delivery Dashboard ──────────────────────────────────────────────────
    availableOrders: "उपलब्ध आर्डर",
    myDeliveries: "मेरी डिलीवरी",
    acceptOrder: "स्वीकार करें",
    markDelivered: "डिलीवर किया",
    earningsToday: "आज की कमाई",
    totalDeliveries: "कुल डिलीवरी",
    pendingPickup: "पिकअप बाकी",
    deliveryMap: "डिलीवरी नक्शा",
    noAvailableOrders: "अभी कोई उपलब्ध ऑर्डर नहीं।",
    noActiveDeliveries: "कोई सक्रिय डिलीवरी नहीं।",
    pickupFrom: "यहाँ से लें",
    deliverTo: "यहाँ पहुंचाएं",
  },

  mr: {
    // App Shell
    appName: "अॅग्रीब्रिज", beta: "बीटा",
    farmer: "शेतकरी", consumer: "ग्राहक", deliveryAgent: "डिलिव्हरी एजंट",
    farmerPortal: "🌾 शेतकरी पोर्टल", consumerPortal: "🛒 ग्राहक पोर्टल", deliveryPortal: "🚚 डिलिव्हरी पोर्टल",
    logout: "लॉग आउट", darkMode: "डार्क मोड", lightMode: "लाइट मोड",

    // Nav
    home: "मुखपृष्ठ", myProducts: "माझी उत्पादने", farmDashboard: "शेती डॅशबोर्ड",
    aiHub: "AI हब", mandiPrices: "मंडी भाव", farmSimulator: "शेती सिम्युलेटर",
    farmingAcademy: "शेती अकादमी", messages: "संदेश", govtSchemes: "सरकारी योजना",
    weather: "हवामान", browseMarket: "बाजार पहा", livePrices: "थेट भाव",
    mapRoutes: "नकाशा आणि मार्ग", myOrders: "माझे ऑर्डर", wishlist: "विशलिस्ट",
    deliveryDashboard: "डिलिव्हरी डॅशबोर्ड",

    // Farmer Home
    goodMorning: "शुभ प्रभात", goodAfternoon: "शुभ दुपार", goodEvening: "शुभ संध्याकाळ",
    farmerGreeting: "🌾 शेतकरी डॅशबोर्ड", readyToSell: "आज विक्रीसाठी तयार?",
    totalRevenue: "एकूण उत्पन्न", totalOrders: "एकूण ऑर्डर",
    pendingOrders: "प्रलंबित ऑर्डर", lowStockAlert: "कमी स्टॉक सूचना",
    quickActions: "⚡ त्वरित कृती", todaysTip: "💡 आजची शेती टिप",
    recentOrders: "📦 अलीकडील प्राप्त ऑर्डर",
    noOrdersYet: "अद्याप कोणतेही ऑर्डर नाही — उत्पादने नोंदवा!",
    listProducts: "+ उत्पाद नोंदवा",
    ordersCount: "दिलेले ऑर्डर", spentTotal: "खर्च केलेली रक्कम", wishlistCount: "विशलिस्ट आयटम",
    todaysDeals: "🔥 आजचे ऑफर", latestOrders: "📋 ताजे ऑर्डर",
    shopNow: "आता खरेदी करा", noOrders: "अद्याप कोणतेही ऑर्डर नाही.",
    farmingTip1: "पिकांना सकाळी लवकर पाणी द्या — यामुळे ३०% बाष्पीभवन कमी होते.",
    farmingTip2: "प्रत्येक हंगामात पीक बदला — यामुळे मातीचे आरोग्य आणि कीड नियंत्रण सुधारते.",
    farmingTip3: "खत घालण्यापूर्वी मातीचे pH तपासा — आदर्श श्रेणी ६.०–७.० आहे.",
    farmingTip4: "ठिबक सिंचनाने पूर सिंचनाच्या तुलनेत ४०–६०% पाणी वाचते.",
    farmingTip5: "शेताभोवती झेंडूची फुले लावा — ते नैसर्गिकरीत्या कीटक दूर ठेवतात.",
    farmingTip6: "पीक डायरी ठेवा — यामुळे चांगले निर्णय घेण्यास मदत होते.",
    cropCalendar: "📅 पीक कॅलेंडर",
    currentSeason: "सध्याचा हंगाम",
    kharif: "खरीप (जून–ऑक्टोबर)", rabi: "रब्बी (नोव्हेंबर–मार्च)", zaid: "झायद (मार्च–जून)",
    suggestedCrops: "सुचवलेली पिके",
    marketPulse: "📈 बाजार स्पंदन",

    // Consumer Home
    shopper: "खरेदीदार",
    freshProduce: "शेतकऱ्यांकडून थेट ताजी उत्पादने",
    productsAvailable: "उत्पादने उपलब्ध",
    browseMarketBtn: "🛒 ताजा बाजार पहा",
    liveRates: "📈 थेट भाव",
    ordersCount: "ऑर्डर", spentTotal: "खर्च", wishlistCount: "विशलिस्ट",
    todaysDeals: "🔥 आजचे सर्वोत्तम डील",
    topRated: "⭐ सर्वोच्च रेटेड",
    featuredFarmers: "👨‍🌾 आमचे शेतकरी",
    trackOrder: "ऑर्डर ट्रॅक करा",
    continueShopping: "खरेदी सुरू ठेवा",
    latestOrders: "📋 अलीकडील ऑर्डर",
    dealBadge: "डील",
    verified: "✓ सत्यापित",
    directFarmer: "🌾 थेट शेतकऱ्याकडून",
    addToCart: "कार्टमध्ये टाका",
    addedToCart: "जोडले!",
    inCart: "कार्टमध्ये",
    inStock: "उपलब्ध", outOfStock: "अनुपलब्ध",
    perKg: "/किलो", perPiece: "/नग", perLitre: "/लिटर",

    // Marketplace
    freshMarket: "🛒 ताजा बाजार",
    searchProducts: "उत्पादने शोधा...",
    filters: "फिल्टर",
    category: "श्रेणी", priceRange: "किंमत श्रेणी", minRating: "किमान रेटिंग",
    sortBy: "क्रमवारी", inStockOnly: "फक्त उपलब्ध",
    applyFilters: "फिल्टर लावा", reset: "रीसेट",
    newestFirst: "नवीनतम प्रथम", priceLowHigh: "किंमत: कमी→अधिक",
    priceHighLow: "किंमत: अधिक→कमी", topRatedSort: "सर्वोच्च रेटेड", inStockSort: "उपलब्ध",
    noProductsFound: "कोणतेही उत्पादन सापडले नाही",
    clearFilters: "फिल्टर काढा",

    // Cart
    myCart: "माझी कार्ट", cartEmpty: "आपली कार्ट रिकामी आहे",
    browseProducts: "उत्पादने पहा",
    subtotal: "उप-एकूण", gst: "GST (5%)", deliveryFree: "डिलिव्हरी मोफत",
    total: "एकूण", proceedCheckout: "चेकआउट करा",
    couponCode: "कूपन कोड", applyCoupon: "लावा",
    couponApplied: "✅ कूपन लागू!", couponInvalid: "❌ अवैध कूपन",
    discount: "सवलत",
    estimatedDelivery: "अंदाजे डिलिव्हरी: ३-५ दिवस",

    // Checkout
    checkout: "चेकआउट",
    step1: "डिलिव्हरी पत्ता", step2: "पेमेंट", step3: "ऑर्डर पुष्टी",
    fullName: "पूर्ण नाव", phone: "फोन नंबर",
    houseFlat: "घर / फ्लॅट / इमारत",
    areaStreet: "परिसर / रस्ता / वसाहत",
    city: "शहर", pincode: "पिनकोड", state: "राज्य",
    saveAddress: "हा पत्ता जतन करा",
    savedAddresses: "जतन केलेले पत्ते", useThisAddress: "हा वापरा",
    paymentMethod: "पेमेंट पद्धत",
    upi: "UPI", card: "कार्ड", netBanking: "नेट बँकिंग",
    cod: "रोख डिलिव्हरीवर", wallet: "वॉलेट",
    upiId: "UPI ID टाका", scanQR: "किंवा QR कोड स्कॅन करा",
    cardNumber: "कार्ड नंबर", expiryDate: "कालबाह्यता (MM/YY)", cvv: "CVV",
    selectBank: "बँक निवडा",
    walletBalance: "वॉलेट शिल्लक",
    orderSummary: "ऑर्डर सारांश", deliveryTo: "डिलिव्हरी पत्ता",
    payUsing: "पेमेंट पद्धत",
    placeOrder: "ऑर्डर द्या",
    placingOrder: "ऑर्डर होत आहे...",
    orderSuccess: "ऑर्डर यशस्वीरीत्या दिला! 🎉",
    orderId: "ऑर्डर ID", expectedDelivery: "अपेक्षित डिलिव्हरी",
    downloadInvoice: "चलान डाउनलोड करा",
    trackOrderBtn: "ऑर्डर ट्रॅक करा",
    continueShopping2: "खरेदी सुरू ठेवा",

    // My Orders
    myOrdersTitle: "माझे ऑर्डर",
    noOrders: "अद्याप कोणतेही ऑर्डर नाही",
    shopNow: "आता खरेदी करा",
    orderDate: "ऑर्डर तारीख", orderStatus: "स्थिती", orderTotal: "एकूण",
    reorder: "पुन्हा ऑर्डर",
    delivered: "पोहोचले", pending: "प्रलंबित", processing: "प्रक्रियेत",
    shipped: "पाठवले", cancelled: "रद्द",

    // Wishlist
    myWishlist: "माझी विशलिस्ट",
    noWishlist: "विशलिस्ट रिकामी आहे",
    removeFromWishlist: "काढा",
    addToCartFromWishlist: "कार्टमध्ये टाका",

    // FarmerMarket
    myProductsTitle: "🌾 माझी उत्पादने",
    addProduct: "+ उत्पाद जोडा",
    searchListings: "यादी शोधा...",
    editListing: "यादी संपादित करा",
    addNewProduct: "नवीन उत्पाद जोडा",
    productName: "उत्पादाचे नाव *",
    categoryLabel: "श्रेणी *",
    unit: "एकक",
    retailPrice: "किरकोळ किंमत (₹) *",
    bulkPrice: "घाऊक किंमत (₹)",
    stockQty: "स्टॉक प्रमाण",
    minBulkQty: "किमान घाऊक प्रमाण",
    imageUrl: "प्रतिमा URL",
    imagePreview: "पूर्वावलोकन",
    saveListing: "जतन करा",
    saving: "जतन होत आहे...",
    cancel: "रद्द करा",
    topSeller: "🏆 टॉप सेलर", lowStock: "⚠️ कमी स्टॉक", newTag: "✨ नवीन",
    noListings: "अद्याप कोणतीही यादी नाही — पहिले उत्पाद जोडा!",
    ordersReceived: "प्राप्त ऑर्डर",
    buyer: "खरेदीदार", quantity: "प्रमाण", unitPrice: "एकक किंमत",

    // Misc
    loading: "लोड होत आहे...", error: "त्रुटी", retry: "पुन्हा प्रयत्न करा",
    viewAll: "सर्व पहा", seeMore: "अधिक पहा",
    copied: "कॉपी झाले!", shareApp: "अॅग्रीब्रिज शेअर करा",
    poweredByAI: "AI द्वारे समर्थित",
    allRights: "अॅग्रीब्रिज — भारतीय शेतीला सशक्त करणे",

    // Weather & Logistics
    weatherTitle: "🌦️ हवामान आणि लॉजिस्टिक्स",
    weatherSubtitle: "रियल-टाइम हवामान सूचना आणि वाहतूक खर्च कॅलकुलेटर",
    liveWeather: "थेट हवामान",
    customCity: "कस्टम शहर...",
    search: "शोधा",
    fetchingWeather: "हवामान लोड होत आहे...",
    todaysFarmingAdvisory: "🌾 आजचे शेती सल्ला",
    feelsLike: "वाटते",
    humidity: "आर्द्रता", wind: "वारा", visibility: "दृश्यमानता",
    transportCalc: "वाहतूक खर्च कॅलकुलेटर",
    originLabel: "📍 मूळ ठिकाण (शेत)",
    destinationLabel: "🎯 गंतव्य (बाजार/खरेदार)",
    vehicleType: "🚚 वाहन प्रकार",
    calcTransport: "📦 वाहतूक खर्च काढा",
    calculating: "गणना होत आहे...",
    transportEstimate: "🧾 वाहतूक अंदाज",
    distance: "अंतर", duration: "वेळ", rate: "दर", estCost: "अंदाजित खर्च",
    route: "मार्ग",
    aboutCalc: "ℹ️ ह्या कॅलकुलेटरबद्दल",
    aboutCalcDesc: "वास्तविक रस्ता अंतर काढण्यासाठी Google Maps चा वापर करतो। दर भारतातील सरासरी दरांवर आधारित आहेत.",
    allMinistries: "सर्व मंत्रालये",

    // Govt Schemes
    schemesTitle: "सरकारी शेती योजना",
    schemesSubtitle: "शेतकर्यांसाठी सक्रिय योजना आणि अनुदान",
    searchSchemes: "योजना शोधा...",
    activeSchemes: "सक्रिय योजना",
    ministries: "मंत्रालये",
    beneficiaries: "लाभार्थी",
    showing: "दाखवत आहे",
    scheme: "योजना", schemes: "योजना",
    applyNow: "अर्ज करा",
    benefit: "लाभ", eligibility: "पात्रता", deadline: "अंतिम तारीख",
    noSchemesFound: "कोणतीही योजना सापडली नाही",

    // Chat
    chatTitle: "💬 संदेश",
    chatSubtitle: "शेतकरी आणि खरेदारांशी थेट संपर्क साधा",
    selectConversation: "चॅट सुरू करण्यासाठी संभाषण निवडा",
    typeMessage: "संदेश लिहा...",
    send: "पाठवा",
    online: "ऑनलाइन", offline: "ऑफलाइन",
    noMessages: "अजून संदेश नाहीत. नमस्कार करा!",
    farmers: "शेतकरी", buyers: "खरेदार", all: "सर्व",

    // Map
    mapTitle: "🗺️ शेत आणि बाजार नकाशा",
    mapSubtitle: "जवळचे शेतकरी, बाजार आणि डिलिव्हरी रूट शोधा",
    mapLoading: "नकाशा लोड होत आहे...",
    showFarmers: "शेतकरी दाखवा",
    showMarkets: "बाजार दाखवा",
    showRoutes: "मार्ग दाखवा",
    directions: "दिशा-निर्देश",
    viewOnMap: "नकाश्यावर पहा",

    // FarmSimulator
    simTitle: "🚜 शेती सिम्युलेटर",
    simSubtitle: "पुढील हंगामासाठी शेती अनुकरण करा",
    cropType: "पिकाचा प्रकार",
    landSize: "जमिनीचा आकार (एकर)",
    irrigationType: "सिंचनाचा प्रकार",
    soilType: "मातीचा प्रकार",
    simulate: "अनुकरण करा",
    simulationResult: "अनुकरण परिणाम",
    expectedYield: "अपेक्षित उत्पन्न",
    estimatedProfit: "अंदाजित नफा",
    waterRequirement: "पाण्याची गरज",
    fertilizerCost: "खताचा खर्च",
    laborCost: "मजुरी खर्च",
    totalCost: "एकूण खर्च",
    netProfit: "निव्वळ नफा",
    riskLevel: "जोखीम पातळी",
    recommendations: "शिफारसी",

    // Farming Tutorials
    tutorialsTitle: "🎓 शेती अकादमी",
    tutorialsSubtitle: "आधुनिक शेती तंत्रे शिका",
    allCategories: "सर्व",
    homeFarming: "घरी शेती",
    microFarming: "सूक्ष्म शेती",
    organic: "सेंद्रिय",
    hydroponics: "हायड्रोपोनिक्स",
    terrace: "गच्ची शेती",
    watchNow: "आता पहा",
    readMore: "अधिक वाचा",
    duration: "कालावधी",
    difficulty: "कठिणता",
    beginner: "प्रारंभिक", intermediate: "मध्यम", advanced: "प्रगत",
    noTutorials: "कोणतेही ट्यूटोरियल सापडले नाही.",

    // AI Hub
    aiHubTitle: "🤖 AI हब",
    aiHubSubtitle: "हुशार शेतीसाठी AI उपकरणे",
    fertilizerAdvisor: "खत सल्लागार",
    cropDiagnosis: "पिक रोग निदान",
    yieldPredictor: "उत्पन्न अंदाजक",
    soilAnalysis: "माती विश्लेषण",
    farmingChatbot: "शेती सहाय्यक",
    analyzeNow: "विश्लेषण करा",
    analyzing: "विश्लेषण होत आहे...",
    result: "परिणाम",
    cropName: "पिकाचे नाव",
    soilTypeLabel: "मातीचा प्रकार",
    symptomDesc: "लक्षणे वर्णन करा...",
    uploadPhoto: "फोटो अपलोड करा",

    // Farmer Dashboard
    dashboardTitle: "📊 शेती डॅशबोर्ड",
    salesOverview: "विक्री आढावा",
    inventoryStatus: "साठा स्थिती",
    revenueChart: "उत्पन्न तक्ता",
    topProducts: "शीर्ष उत्पादने",
    stockLevel: "साठा पातळी",
    last7Days: "मागील ७ दिवस",
    last30Days: "मागील ३० दिवस",
    thisYear: "हे वर्ष",

    // Login
    welcomeTitle: "AgriBridge मध्ये आपले स्वागत",
    iAmA: "मी आहे...",
    farmerDesc: "पिक विका, शेती व्यवस्थापन, AI उपकरणे वापरा",
    consumerDesc: "शेतकर्यांकडून थेट ताजी उत्पादने खरेदी करा",
    deliveryDesc: "शेतकर्यांकडून ऑर्डर घ्या आणि ग्राहकांपर्यंत पोहेचवा",
    continueAs: "पुढे जा",
    yourName: "तुमचे नाव (एच्छिक)",
    emailAddress: "ईमेल पत्ता *",
    sendOtp: "OTP पाठवा →",
    checkInbox: "इनबॉक्स तपासा",
    sentCode: "आपणाला 6-अंकी कोड पाठवला",
    devMode: "⚙️ डेव मोड — OTP:",
    verifyLogin: "पडताळणी करा आणि लॉगिन करा ✓",
    resendOtp: "OTP पुन्हा पाठवा",
    resendIn: "OTP पुन्हा पाठवा",
    secureNote: "🔒 सुरक्षित · पासवर्ड नाही · OTP 10 मिनिटांत एक्सपायर",
    back: "← मागे",

    // Delivery Dashboard
    deliveryAgentPortal: "डिलिव्हरी डॅशबोर्ड",
    availableOrders: "📦 उपलब्ध",
    myDeliveries: "🚚 माझ्या डिलिव्हरी",
    earnings: "💰 कमाई",
    totalDeliveries: "एकूण डिलिव्हरी",
    completedDeliveries: "पूर्ण",
    activeDeliveries: "सक्रिय",
    totalEarned: "एकूण कमाई",
    acceptDelivery: "🚚 डिलिव्हरी स्वीकारा",
    confirmPickup: "📦 पिकअप पुष्टी करा",
    markInTransit: "🚚 मार्गावर मार्क करा",
    markDelivered: "🎉 डिलिव्हरड मार्क करा",
    perDelivery: "प्रति डिलिव्हरी",
    noAvailableOrders: "आता कोणतेही ऑर्डर उपलब्ध नाही",
    noMyDeliveries: "अजून कोणतीही डिलिव्हरी नियुक्त नाही",
    browseAvailable: "📦 उपलब्ध ऑर्डर पहा",
    pickup: "पिकअप", drop: "ड्रॉप",
    agentAssigned: "एजंट नियुक्त",
    orderPickedUp: "ऑर्डर उचलला",
    outForDelivery: "डिलिव्हरीसाठी निघाले",
    refreshing: "लोड होत आहे...", refresh: "↳ रिफ्रेश",

    // FarmerDashboard extra
    analyticsDashboard: "विश्लेषण डॅशबोर्ड",
    dashboardSubtitle: "रिअल-टाइम माहिती · AI भाव ट्रॅकर · शेती बुद्धिमत्ता",
    overview: "आढावा", insights: "अंतर्दृष्टी",
    platformOverview: "प्लॅटफॉर्म आढावा",
    allTimeEarnings: "सर्व काळातील कमाई",
    fulfilledOrders: "पूर्ण ऑर्डर",
    avgRating: "सरासरी रेटिंग",
    customerSatisfaction: "ग्राहक समाधान",
    activeProducts: "सक्रिय उत्पादने",
    listedOnMarket: "बाजारात नोंदवलेले",
    thisWeeksRevenue: "या आठवड्याचे उत्पन्न",
    products: "उत्पादने", orders: "ऑर्डर", revenue: "उत्पन्न", buyers: "खरेदीदार",

    // FarmSimulator extra
    virtualFarmSim: "व्हर्च्युअल शेती सिम्युलेटर",
    farmSimDesc: "शेत माहिती भरा → AI 5 उत्तम पीक पर्याय देतो",
    locationField: "🌍 स्थान (शहर, राज्य)",
    landSizeField: "📐 जमीन आकार (एकर)",
    budgetField: "💰 बजेट (₹)",
    soilTypeField: "🏔️ मातीचा प्रकार",
    seasonField: "🌦️ हंगाम",
    simulating: "Groq AI कडून 5 पिकांचे अनुकरण होत आहे...",
    runSimulation: "🚜 शेती सिम्युलेशन चालवा",
    aiRecommendedCrops: "5 AI-शिफारस केलेली पिके (योग्यतेनुसार)",

    // FarmingTutorials extra
    yourLevel: "🎯 तुमची पातळी",
    topicOptional: "विषय (ऐच्छिक)",
    generating: "तयार होत आहे…",
    regenerate: "पुन्हा तयार करा",
    loadTutorials: "ट्यूटोरियल लोड करा",
    welcomeAcademy: "शेती अकादमीत आपले स्वागत",
    academyDesc: "घरची शेती, सूक्ष्म शेती, हायड्रोपोनिक्स, गच्ची बागवानी यासाठी AI ट्यूटोरियल मिळवा।",
    loadAiTutorials: "🌱 AI ट्यूटोरियल लोड करा",

    // AIHub extra
    aiFarmIntelligence: "AI शेती बुद्धिमत्ता",
    aiSystemsOnline: "AI सिस्टम ऑनलाइन",
    yieldPredictor: "📈 उत्पन्न अंदाजक",
    fertilizerAdvisor: "🌱 खत सल्लागार",
    soilHealth: "🔬 माती आरोग्य",
    cropDoctor: "🩺 पीक डॉक्टर",
    aiChatbot: "🤖 AI चॅटबॉट",
    farmSimulator: "🚜 शेती सिम्युलेटर",
    aiHubSubtitle: "अग्रगण्य मॉडेल्सद्वारे चालवलेली 6 AI साधने",

    // MapView
    mapPageTitle: "🗺️ अॅग्रीब्रिज नकाशा — पुणे आणि बिबवेवाडी",
    mapPageSubtitle: "बिबवेवाडी, धायरी, कात्रज आणि पुण्याच्या आसपासच्या भागातील स्थानिक शेते, मंडया, डिलिव्हरी पार्टनर आणि खरेदीदार",
    mapSearchPlaceholder: "🔍 नाव किंवा शहर शोधा...",
    mapShow10km: "10 किमी त्रिज्या दाखवा",
    mapLocations: "ठिकाण", mapLocationsPlural: "ठिकाणे",
    mapNoLocations: "कोणतेही ठिकाण सापडले नाही.",
    mapLegend: "आख्यायिका",
    mapTypeFarm: "शेत", mapTypeStore: "दुकान / मंडी", mapTypeDelivery: "डिलिव्हरी पार्टनर", mapTypeBuyer: "खरेदीदार",
    mapFilterAll: "सर्व", mapFilterFarms: "शेते", mapFilterStores: "दुकाने", mapFilterDelivery: "डिलिव्हरी", mapFilterBuyers: "खरेदीदार",
    mapDetailDescription: "वर्णन", mapDetailStock: "साठा", mapDetailTimings: "वेळ",
    mapDetailFleet: "वाहन", mapDetailRate: "दर", mapDetailContact: "संपर्क", mapDetailRating: "रेटिंग",
    mapPoweredBy: "नकाशा Leaflet.js + OpenStreetMap द्वारे चालवला — पूर्णपणे मोफत, API की आवश्यक नाही. तपशील पाहण्यासाठी कोणत्याही मार्करवर किंवा साइडबार कार्डवर क्लिक करा.",

    // FarmerDashboard hardcoded strings
    loadingDashboard: "डॅशबोर्ड लोड होत आहे...",
    farmingTipLabel: "💡 शेतीची टिप",
    monthlyRevenue: "मासिक उत्पन्न (₹)",
    mostSoldCrops: "सर्वाधिक विकली गेलेली पिके (प्रमाण किलोमध्ये)",
    avgCustomerRating: "उत्पादनानुसार सरासरी रेटिंग",
    cropSalesDistribution: "पीक विक्री वितरण",
    revenueBreakdown: "💰 उत्पन्न विवरण",
    retailSales: "किरकोळ विक्री", bulkB2B: "घाऊक/B2B", avgPerOrder: "प्रति ऑर्डर सरासरी",
    productHealth: "📦 उत्पाद आरोग्य",
    activeListings: "सक्रिय नोंदी", returnRate: "परतावा दर",
    farmStatus: "🌾 शेत स्थिती",
    currentSeasonLabel: "सध्याचा हंगाम", nextHarvest: "पुढील कापणी", mspCoverage: "MSP कव्हरेज",
    farmPerformanceScore: "शेती कामगिरी गुण",
    revenueGrowth: "उत्पन्न वाढ",
    productDiversity: "उत्पाद विविधता", marketReach: "बाजार पोहोच", onTimeDelivery: "वेळेवर डिलिव्हरी",
    performanceRadar: "कामगिरी राडार",
    aiGeneratedInsights: "🧠 AI-निर्मित अंतर्दृष्टी",
    noRevenueData: "अद्याप उत्पन्न डेटा नाही",
    noSalesData: "अद्याप विक्री डेटा नाही",
    noRatingData: "अद्याप रेटिंग डेटा नाही",
    noData: "डेटा नाही",
    vsLastMonth: "% मागील महिन्याच्या तुलनेत",
    marketAlert: "बाजार सूचना: वाढते भाव",
    marketAlertDesc: "या आठवड्यात टोमॅटो आणि कांद्याचे भाव 15-20% वाढले. साठवलेला स्टॉक आता विकण्याचा विचार करा.",
    customerSatisfaction: "ग्राहक समाधान",
    products: "उत्पादने", orders: "ऑर्डर", revenue: "उत्पन्न", rating: "रेटिंग",

    // ── ConsumerMarket strings ──────────────────────────────────────────────
    freshMarket: "ताजा बाजार",
    farmFreshDirect: "शेतातून थेट ताजी उत्पादने तुमच्यापर्यंत",
    searchPlaceholder: "भाज्या, फळे, धान्य शोधा…",
    filters: "फिल्टर",
    showingProducts: "दाखवत आहे",
    productsLabel: "उत्पादने",
    forSearch: "साठी",
    noProductsFound: "कोणतेही उत्पादन सापडले नाही",
    tryDifferentFilters: "वेगळे फिल्टर किंवा शोध शब्द वापरा",
    clearFilters: "फिल्टर साफ करा",
    addToCart: "कार्टमध्ये जोडा",
    addedToCart: "कार्टमध्ये जोडले!",
    myCart: "माझी कार्ट",
    cartEmpty: "तुमची कार्ट रिकामी आहे",
    addFreshProduce: "सुरू करण्यासाठी ताजी उत्पादने जोडा!",
    subtotal: "उप-एकूण",
    delivery: "डिलिव्हरी",
    deliveryFree: "मोफत",
    total: "एकूण",
    proceedToCheckout: "चेकआउट करा",
    estDelivery: "अंदाजे डिलिव्हरी: 3-5 कार्य दिवस",
    couponPlaceholder: "कूपन कोड (उदा. FRESH10)",
    applyCoupon: "लागू करा",
    couponApplied: "कूपन लागू झाला!",
    couponInvalid: "अवैध कूपन कोड.",
    inCart: "कार्टमध्ये",
    farmFreshBadge: "शेत-ताजे",
    retailLabel: "किरकोळ",
    bulkLabel: "घाऊक",
    perUnit: "प्रति",
    minBulk: "किमान",
    hideReviews: "पुनरावलोकने लपवा",
    reviewsRate: "पुनरावलोकने आणि रेटिंग",
    yourReview: "तुमचे पुनरावलोकन",
    shareExperience: "तुमचा अनुभव सांगा…",
    submitReview: "पुनरावलोकन सबमिट करा",
    categoryLabel: "श्रेणी",
    priceRange: "किंमत श्रेणी",
    minimumRating: "किमान रेटिंग",
    sortBy: "क्रमवारी लावा",
    inStockOnly: "फक्त स्टॉकमध्ये",
    resetBtn: "रीसेट",
    applyFilters: "फिल्टर लागू करा",
    newestFirst: "नवीन प्रथम",
    priceLowHigh: "किंमत: कमी→जास्त",
    priceHighLow: "किंमत: जास्त→कमी",
    topRated: "सर्वोच्च रेटिंग",
    inStock: "स्टॉकमध्ये",
    itemsInWishlist: "आयटम तुमच्या विशलिस्टमध्ये",
    itemInWishlist: "आयटम तुमच्या विशलिस्टमध्ये",
    allCategories: "सर्व",
    gstLabel: "जीएसटी (5%)",

    // ── HomePage strings ────────────────────────────────────────────────────
    farmerHeroLine1: "तुमची",
    farmerHeroLine2: "शेती",
    farmerHeroLine3: "उत्पन्नात बदला।",
    consumerHeroLine1: "शेतातील",
    consumerHeroLine2: "ताजी उत्पादने,",
    consumerHeroLine3: "थेट तुमच्यासाठी।",
    farmerHeroDesc: "12 वेगळ्या अॅप्स वापरणे बंद करा. AgriBridge तुमची पिके, बाजार, AI अंतर्दृष्टी आणि मंडी डेटा एका शक्तिशाली प्लॅटफॉर्मवर आणतो.",
    farmerHeroAccent: "आधीच जास्त कमाई करत असलेल्या 2,400+ भारतीय शेतकऱ्यांमध्ये सामील व्हा.",
    farmerCta1: "🌾 बाजार पहा",
    farmerCta2: "▶ AI साधने वापरा",
    farmerFeature1: "✓ सामील होणे मोफत",
    farmerFeature2: "✓ कोणतीही सदस्यता नाही",
    farmerFeature3: "✓ AI-चालित अंतर्दृष्टी",
    consumerHeroDesc: "सुपरमार्केटमध्ये जास्त पैसे देणे बंद करा. AgriBridge तुम्हाला सत्यापित भारतीय शेतकऱ्यांशी थेट जोडतो — ताजी उत्पादने, प्रामाणिक किंमती, दरवाजापर्यंत डिलिव्हरी.",
    consumerHeroAccent: "किरकोळ पेक्षा 40% पर्यंत बचत करा — कोणताही दलाल नाही.",
    consumerCta1: "🛒 ताजी उत्पादने पहा",
    consumerCta2: "📦 माझे ऑर्डर",
    verifiedFarmers: "✓ केवळ सत्यापित शेतकरी",
    freshGuaranteed: "✓ ताजेपणाची हमी",
    freeReturns: "✓ मोफत परतावा",
    livePricesBadge: "थेट भाव",
    platformFeaturesBadge: "प्लॅटफॉर्म वैशिष्ट्ये",
    everythingFarmerNeeds: "शेतकऱ्याची प्रत्येक गरज",
    platformFeaturesDesc: "AI-चालित पीक काळजीपासून थेट बाजार प्रवेशापर्यंत — एक प्लॅटफॉर्म, असीमित शक्यता.",
    builtForEveryone: "सर्वांसाठी बनवलेले",
    whoUsesTitle: "AgriBridge कोण वापरतो?",
    forFarmers: "शेतकऱ्यांसाठी",
    forConsumers: "ग्राहकांसाठी",
    forBusinesses: "व्यवसायांसाठी",
    farmerTab1: "🌾 मिनिटांत तुमची उत्पादने सूचीबद्ध करा — हजारो खरेदीदारांपर्यंत पोहोचा",
    farmerTab2: "🤖 AI पीक काळजी: खत वेळापत्रक + रोग निदान",
    farmerTab3: "💰 पारदर्शी बाजार डेटाने उचित किंमत मिळवा",
    farmerTab4: "🏛️ तुम्ही पात्र असलेल्या प्रत्येक सरकारी योजनेचा शोध घ्या",
    farmerTab5: "🌦️ अचूक हवामान अंदाजाने कापणीची योजना बनवा",
    consumerTab1: "🛒 सत्यापित भारतीय शेतकऱ्यांकडून थेट ताजी उत्पादने खरेदी करा",
    consumerTab2: "💵 किरकोळपेक्षा 40% पर्यंत बचत करा — कोणताही दलाल नाही",
    consumerTab3: "🚚 3-5 कार्य दिवसांत दरवाजापर्यंत डिलिव्हरी",
    consumerTab4: "⭐ प्रत्येक शेतकऱ्याचे रेटिंग आणि पुनरावलोकने",
    consumerTab5: "📦 रिअल टाइममध्ये ऑर्डर ट्रॅक करा",
    businessTab1: "🏭 शेतातून थेट घाऊक खरेदी",
    businessTab2: "📊 रिअल-टाइम कमोडिटी किंमत माहिती",
    businessTab3: "🤝 34 राज्यांमध्ये सत्यापित शेतकरी नेटवर्क",
    businessTab4: "📜 डिजिटल करार आणि गुणवत्ता प्रमाणपत्रे",
    businessTab5: "🔁 आवर्ती ऑर्डर व्यवस्थापन डॅशबोर्ड",
    startAsFarmer: "शेतकरी म्हणून सुरू करा →",
    shopFreshProduce: "ताजी उत्पादने खरेदी करा →",
    contactB2B: "B2B साठी संपर्क करा →",
    yourDashboard: "तुमचा डॅशबोर्ड",
    manageProducts: "उत्पादने व्यवस्थापित करा →",
    fullDashboard: "संपूर्ण डॅशबोर्ड →",
    recentOrdersLabel: "अलीकडील ऑर्डर",
    thisSeasonLabel: "या हंगामात",
    allTimeLabel: "सर्व वेळ",
    needsActionLabel: "कृती आवश्यक",
    itemsLt10: "10 पेक्षा कमी वस्तू",
    justJoined: "नुकतेच सामील झाले",
    classicView: "📋 क्लासिक व्ह्यू",
    modernView: "🆕 मॉडर्न व्ह्यू",
    ourFarmers: "आमचे शेतकरी",
    viewAll: "सर्व पहा",
    buyNow: "आता खरेदी करा →",
    shopNow: "आता खरेदी करा →",
    noOrdersYet: "अद्याप कोणतेही ऑर्डर नाही",
    messageBtn: "संदेश",
    verifiedBadge: "✓✓ सत्यापित",
    ordersCount: "ऑर्डर",
    featureMarketTitle: "ताजा बाजार",
    featureMarketDesc: "थेट ताजी उत्पादने खरेदी आणि विक्री करा. थेट इन्व्हेंटरी ट्रॅकिंगसह किरकोळ आणि घाऊक किंमती.",
    featureAITitle: "AI शेती बुद्धिमत्ता",
    featureAIDesc: "खत वेळापत्रक मिळवा, पीक रोगांचे निदान करा आणि 24/7 AI कृषी तज्ञाशी गप्पा मारा.",
    featureWeatherTitle: "हवामान आणि अंदाज",
    featureWeatherDesc: "तुमच्या शेतासाठी हायपरलोकल 7-दिवस अंदाज, माती तापमान आणि हवामान सूचना.",
    featureMapTitle: "शेती नकाशा आणि मार्ग",
    featureMapDesc: "इंटरएक्टिव्ह नकाशावर तुमचे शेत पहा, डिलिव्हरी मार्ग ट्रॅक करा आणि जवळच्या मंड्या शोधा.",
    totalRevenueCard: "एकूण उत्पन्न",
    activeFarmers: "सक्रिय शेतकरी",
    earningsView: "📊 कमाई पहा",
    totalSavings: "एकूण बचत",
    browseMarketCard: "बाजार पहा",
    justOrdered: "नुकतेच ऑर्डर केले",
    newBadge: "नवीन:",
    newAICropDoctor: "नवीन: AI पीक डॉक्टर 2.0 — आता उपलब्ध",
    newFarmToDoor: "नवीन: शेत-ते-दार डिलिव्हरी — आता उपलब्ध",
    searchByVoice: "आवाजाने शोधा",
    byFarmer: "यांनी",

    // ── FarmerMarket strings ────────────────────────────────────────────────
    myListings: "माझ्या नोंदी",
    addProduct: "उत्पादन जोडा",
    editProduct: "उत्पादन संपादित करा",
    deleteProduct: "उत्पादन हटवा",
    productName: "उत्पादनाचे नाव",
    description: "वर्णन",
    category: "श्रेणी",
    retailPrice: "किरकोळ किंमत (₹/घटक)",
    bulkPrice: "घाऊक किंमत (₹/घटक)",
    minBulkQty: "किमान घाऊक प्रमाण",
    stockQty: "साठा (किलो)",
    unit: "घटक",
    imageUrl: "प्रतिमा URL",
    saveProduct: "उत्पादन जतन करा",
    cancelBtn: "रद्द करा",
    deleteConfirm: "हे उत्पादन हटवायचे?",
    noListings: "अद्याप कोणत्याही नोंदी नाहीत. तुमचे पहिले उत्पादन जोडा!",
    addFirstProduct: "पहिले उत्पादन जोडा",
    perKg: "/किलो",
    kgStock: "किलो साठा",
    reviewCount: "पुनरावलोकने",
    loadingProducts: "तुमची उत्पादने लोड होत आहेत...",
    productAdded: "उत्पादन जोडले!",
    productUpdated: "उत्पादन अपडेट झाले!",
    productDeleted: "उत्पादन हटवले.",
    saveChanges: "बदल जतन करा",
    fromOrders: "सर्व ऑर्डरमधून",
    productsLabel: "उत्पादने",
    noProductsFoundFm: "जुळणारी उत्पादने नाहीत",
    tryDifferentFilters: "वेगळा शोध किंवा फिल्टर वापरा",
    noOrdersYet: "अद्याप कोणतेही ऑर्डर नाही",

    // ── Checkout / Orders / Wishlist strings ────────────────────────────────
    checkoutTitle: "चेकआउट",
    orderSummary: "ऑर्डर सारांश",
    shippingAddress: "शिपिंग पत्ता",
    fullName: "पूर्ण नाव",
    phone: "फोन",
    addressLine: "पत्ता",
    city: "शहर",
    pincode: "पिनकोड",
    placeOrder: "ऑर्डर करा",
    orderPlaced: "ऑर्डर दिला!",
    orderPlacedDesc: "तुमचा ऑर्डर यशस्वीरीत्या दिला गेला आहे. लवकरच पुष्टी मिळेल.",
    continueShopping: "खरेदी सुरू ठेवा",
    myOrdersTitle: "माझे ऑर्डर",
    noOrdersDesc: "तुम्ही अद्याप कोणतेही ऑर्डर दिले नाहीत.",
    startShopping: "खरेदी सुरू करा",
    orderStatus: "स्थिती",
    orderDate: "तारीख",
    wishlistTitle: "माझी विशलिस्ट",
    wishlistEmpty: "तुमची विशलिस्ट रिकामी आहे.",
    browseProducts: "उत्पादने पहा",
    removeFromWishlist: "हटवा",

    // ── Delivery Dashboard ──────────────────────────────────────────────────
    availableOrders: "उपलब्ध ऑर्डर",
    myDeliveries: "माझ्या डिलिव्हरी",
    acceptOrder: "स्वीकार करा",
    markDelivered: "डिलिव्हर केले",
    earningsToday: "आजची कमाई",
    totalDeliveries: "एकूण डिलिव्हरी",
    pendingPickup: "पिकअप प्रलंबित",
    deliveryMap: "डिलिव्हरी नकाशा",
    noAvailableOrders: "आत्ता कोणतेही उपलब्ध ऑर्डर नाही.",
    noActiveDeliveries: "कोणत्याही सक्रिय डिलिव्हरी नाहीत.",
    pickupFrom: "येथून घ्या",
    deliverTo: "येथे पोहोचवा",
  },
};

/* ─── Context ───────────────────────────────────────────────────────────────── */
export const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem("agribridge-lang") || "en"
  );

  useEffect(() => {
    localStorage.setItem("agribridge-lang", language);
  }, [language]);

  // Translation function — falls back to English if key missing
  const t = (key) =>
    TRANSLATIONS[language]?.[key] ?? TRANSLATIONS.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}

export default LanguageProvider;
